### ISSUE TITLE
Side-loading comments

### ISSUE THREAD

**Issue by esmale** [zendesk/zendesk_api_client_rb#118]
Is it possible with the gem/API to side-load comments when retrieving a ticket or set of tickets?  

Our end-users submit comments on our site, which we preserve there and send to Zendesk through the API.  But our customer service staff works directly through the Zendesk site, so we need to periodically update our local cached copies of the Ticket data and add in any comments that were made on the Zendesk side for display to the end-users.

Is there a way to do that if side-loading the comments isn't an option?

**Comment by ZosionLee** [comment]
This is a problem that when list all tickets, how to find the last audit name??

we can use include last_audits to get last audit id ( author_id ), but we can`t get the author name once time
