### ISSUE TITLE
Returning `nil` on creation of a resource is not very helpful for troubleshooting

### ISSUE THREAD

**Issue by shivpkumar** [zendesk/zendesk_api_client_rb#172]
In `lib/zendesk_api/actions.rb`, the `create` method is as follows:

```ruby
def create(client, attributes = {}, &block)
  create!(client, attributes, &block)
rescue ZendeskAPI::Error::ClientError
  nil
end
```

So, if I do something like this...

```ruby
@client.tickets.create(ticket_params)
```

And there's something wrong with `ticket_params`, then all I'm returned is `nil`.  No explanation of what's wrong with my params or anything.  This makes it pretty difficult to troubleshoot when there is an error.  Would it be possible to return the error instead?  This is probably not how you'd want to do it, but you get the idea :wink: 

```ruby
def create(client, attributes = {}, &block)
  create!(client, attributes, &block)
rescue ZendeskAPI::Error::ClientError => e
  e
end
```

Thanks!

**Comment by joelevering** [comment]
Any update on this? I agree with Shiv that the default behavior is unexpected and makes troubleshooting difficult.

**Comment by steved** [comment]
I don't think returning the error is proper, you should use `model.errors` or the methods that raise. If there is a specific error that isn't being conveyed, then that should be fixed.
