### ISSUE TITLE
Request: Help Center support; here's a temporary workaround

### ISSUE THREAD

**Issue by LouisStAmour** [zendesk/zendesk_api_client_rb#175]
This can serve both as a feature request for http://developer.zendesk.com/documentation/rest_api/hc/introduction.html API support and to document some cheap tricks to add read-only support at least. (Which is all I needed.)

Note: Since categories exist in both, YMMV. We don't use categories, though, so this appears to work well enough for reading. Not yet fully tested. Could probably restrict changes to the new client, but I'm lazy and won't need to use the new and old APIs at the same time in this script.  If you do need to, for example, look up users, you'll have to do it yourself using a client with the usual URL configured, no automatic joins here. E.g. `hc_client.articles.first.author` returns `{"error"=>"InvalidEndpoint", "description"=>"Not found"}` however with an old `client` made the usual way, `client.users.find(id: hc_client.articles.first.author_id)` will work. Or do as I recommend and load and cache all the users so you don't have to make individual requests.

``` ruby
# Redefining classes for hc
module ZendeskAPI
  class Article < Resource; end
  class Section < Resource; end
  class Category
    has_many Section
    has_many Article
  end
  class Section
    has_many Article
    has Category
  end
  class Article
    has :author, :class => User # not sure why I bothered if it doesn't work.
  end
end

hc_client = ZendeskAPI::Client.new do |config|
  config.url = "https://COMPANY-NAME-GOES-HERE.zendesk.com/api/v2/help_center"
  config.username = ""
  config.token = ""
  config.retry = true
  require 'logger'
  config.logger = Logger.new(STDOUT)
end
```

**Comment by voltechs** [comment]
I couldn't get any help from the developers through our contract, so I whipped this up on my own, hope it helps someone else.

You can now call `client.help_desk.categories` etc

```ruby
module ZendeskAPI
  class HelpCenter
    class << self
      def resource_name
        "help_center"
      end

      alias :resource_path :resource_name

      def model_key
        "help_center"
      end
    end

    class Article < Resource; end
    class Section < Resource; end
    class Category < Resource
      namespace 'help_center'

      has_many Section
      has_many Article
    end
    class Section < Resource
      namespace 'help_center'

      has_many Article
      has Category
    end
    class Article < Resource
      namespace 'help_center'

      has :author, class: User

      def self.incremental(client, start_time)
        ZendeskAPI::Collection.new(client, self, path: "help_center/incremental/articles.json?start_time=#{start_time.to_i}")
      end

    end
  end
end
```

**Comment by sidabs** [comment]
is there any update on getting this to be part of the core `ZendeskAPI` module?

**Comment by andresfcamacho** [comment]
Its been a while. Is there any intention on Zendesk's part to include support for Articles?

**Comment by maddox** [comment]
Anyone have a hot tip on how we can extend this to support creating or updating articles vs just listing?

It's a real shame this official client doesn't support the entire API :/

**Comment by srinitude** [comment]
I'm really surprised this hasn't been added to the API yet

**Comment by nogates** [comment]
So sorry for this has taken such a long time to get approved and merged. We have just merged https://github.com/zendesk/zendesk_api_client_rb/pull/428 that adds these the missing Article and Section resources to the client, so I will close this issue.
We will release a new version of the library next week (v.1.27.0)
