### ISSUE TITLE
sideloading users corresponding with requester_id on ticket

### ISSUE THREAD

**Issue by moneydance** [zendesk/zendesk_api_client_rb#181]
Hi i am doing a search here is my code

the querystring is for tickets

`query = @client.search(:query => querystring)`

I would like to side load the users that correspond to the requester_id in the tickets that are given back
I am able to get the information by going through the individual tickets and calling .requester.name but because it's loading the user for every ticket it takes a very long time.

I tried something like this 

`query = @client.search(:query => querystring, :include => :requester)`

but after the query returns all the tickets in console it spits out 

"Missing requester key in response -- cannot side load "

any ideas?

**Comment by dbuskariol** [comment]
Hi @steved!

I am trying to use your suggestions. I have a view and can get all the tickets in that view, but get a key error (`Missing metric_sets key in response -- cannot side load`) when trying to sideload against the view tickets:

```
client.views.find!(id: 360009798273, include: :metric_sets).tickets
```

I can see the Gem is trying to go to `https://{subdomain}.zendesk.com/api/v2/views/{ID}?include=metric_sets` when the URL I am trying to get the Gem to access is `https://{subdomain}.zendesk.com/api/v2/views/{ID}/tickets.json\?include=metric_sets`

`curl`ing the latter URL gets me the results I need the Gem to return. Any suggestions?

**Comment by one-more-alex** [comment]
Having similar issue.
But nowadays documentation says

[Search](https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/) supports sideloads. However, you must specify the type of records searched in the include query parameter to sideload data related to that record type. Specify the type and sideload using the following syntax:

include={type}({sideload})


I run 
zendesk_client.search(query: "type:ticket organization:#{zendesk_organizaton.id}", include: "tickets(requesters)")
and have a warning after execution:
Missing tickets(requesters) key in response -- cannot side load

Is it not supported too, or I made a mistake?
