### ISSUE TITLE
Can't access to Zendesk.

### ISSUE THREAD

**Issue by KimJungHun** [zendesk/zendesk_api_client_rb#207]
Hello.

Now, I can't access to Zendesk.
Now, I am running ubuntu by using AWS.

   client = ZendeskAPI::Client.new do |config|
        config.url = "https://#{interpolated["account"]}.zendesk.com/api/v2"
        config.username = interpolated["agent_email"] #hbywoo@gmail.com
        config.token = interpolated["api_token"] #My API Token
        config.retry = true
        require 'logger'
        config.logger = Logger.new(STDOUT)
      end

puts client.tickets.find(:id => 1)

When I run this code, I got this issue.

Exception during check. undefined method `get' for nil:NilClass: /home/ubuntu/project/huginn/vendor/bundle/ruby/1.9.1/gems/zendesk_api-1.5.1/lib/zendesk_api/actions.rb:104:in `find!'

I can't find reason for it. :(
Can you help me?

**Comment by steved555** [comment]
Can you reproduce this in a standalone script? If not, perhaps one of the dependencies is interfering.

**Comment by sandlerr** [comment]
Please try upgrading your version of Ruby if you are running 1.9.1. You can
look at `.travis.yml` to see which Ruby versions this project is tested on.

**Comment by steved555** [comment]
We actually do test on 1.9.3, ruby uses the 1.9.1 namespace for every 1.9 version above it.

http://stackoverflow.com/questions/8564210/why-are-we-installing-ruby-1-9-2-1-9-3-gems-into-a-1-9-1-folder

It'd be great to isolate this to something in the gem or compatibility issues. If there's anything sensitive you can email "api _at_ zendesk.com"

**Comment by KimJungHun** [comment]
@steved555 @sandlerr Thank you for your help. It is ruby version issue. I used 1.8.3 :(
I changed client.rb of zendesk_api. 
    def build_connection
      build_con = Faraday.new(config.options) do |builder|
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   return build_con
   
When call build_connection, old version of Ruby didn't return object for connection.
I will upgrade Ruby Version. :)
Have a nice day~!!
