### ISSUE TITLE
API doesn't return lists (categories, sections etc) in specified order.

### ISSUE THREAD

**Issue by voltechs** [zendesk/zendesk_api_client_rb#211]

**Comment by steved555** [comment]
Is this for help center, or classic forums? Any endpoint specifically? We should have a fixed order for the default calls to endpoints.

**Comment by voltechs** [comment]
Help Center, https://*.zendesk.com/api/v2/help_center/articles

Given that the order is configurable via the UI, I believe the API should return in the specified order. Otherwise, one would need to recreate the ordering service, redundantly store the order of resources and then apply that order after the fact.

**Comment by steved** [comment]
Hi, are you still seeing this problem? If so, can you send an email to api`_at_`zendesk.com and we'll look into your case more specifically. Thanks!
