### ISSUE TITLE
Ticket query problem

### ISSUE THREAD

**Issue by hlong92** [zendesk/zendesk_api_client_rb#213]
Firstly, I created a ticket by ZendeskAPI::Ticket.new with requester email abc@xyz.io.
Then I queried the ticket by query = ZendeskClient.search(:query => "requester:abc@xyz.io")
But query.fetch.size returns 0. 
I tried to get more times. Finally, I got the right data ticket in than a minute.
I want to get the ticket right away after creating a ticket successful.

**Comment by steved** [comment]
The ticket data will be returned by the creation response, so you don't need to re-query it.

For example,
```
ticket = ZendeskAPI::Ticket.new(client, ....)
ticket.save!

ticket.id # => the new ticket id
ticket.attributes # => full, newly created ticket attributes
```

**Comment by hlong92** [comment]
Oops, many thanks!
