### ISSUE TITLE
Ticket Satisfaction Ratings

### ISSUE THREAD

**Issue by coobstar** [zendesk/zendesk_api_client_rb#214]
Hello,

It would seem from my exploration of the code that it is not possible to create a new satisfaction rating for a ticket using this API.  Anybody know if this is truly the case or am I just a bit dunderheaded when it comes to rails?  It seems my only option is to embed a 'curl' into my server.

**Comment by steved** [comment]
Added the functionality in 1.6.1, see the commit for usage and let me know if you have any problems.
