### ISSUE TITLE
Zendesk API Ruby Search Basics

### ISSUE THREAD

**Issue by jaykilleen** [zendesk/zendesk_api_client_rb#216]
I am struggling with the Zendesk API in my rails app. My setup so far (which is built upon other issues raised here on Github) is as follows.

I have created a `app/models/zendesk.rb` file with the following:

```ruby
require 'zendesk_api'

module Zendesk
  def self.client
    ZendeskAPI::Client.new do |config|
      # Mandatory:

      config.url = "https://usgboral.zendesk.com/api/v2" # e.g. https://mydesk.zendesk.com/api/v2

      # Basic / Token Authentication
      config.username = "admin@domain.com"

      # Choose one of the following depending on your authentication choice
      config.token = Rails.application.secrets.zendesk_api_token

      # Optional:

      # Retry uses middleware to notify the user
      # when hitting the rate limit, sleep automatically,
      # then retry the request.
      config.retry = true

      # Logger prints to STDERR by default, to e.g. print to stdout:
      require 'logger'
      config.logger = Logger.new(STDOUT)

      # Changes Faraday adapter
      # config.adapter = :patron

      # Merged with the default client options hash
      # config.client_options = { :ssl => false }

      # When getting the error 'hostname does not match the server certificate'
      # use the API at https://yoursubdomain.zendesk.com/api/v2
    end
  end
end
```
I have stored my zendesk_api_token in secrets.yml for development, stubbing it out for testing and set as an environment variable on Heroku in production with `zendesk_api_token: <%= ENV['ZENDESK_API_TOKEN'] %>`

I have also added in a method to my User class in `app/models/user.rb` with

```ruby
def zendesk
  Zendesk.client.users.search(:query => self.email)
end
```

Now with that setup, I am right to run `rails console` and play around.

```bash
$ user = User.last
User Load (1.0ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
=> #<User:0x007f04b5a35230> {
  :id => 123456,
  :provider => "provider",
  :uid => "134567891011",
  :email => "admin@domain.com",
  :first_name => "Jay",
  :last_name => "Killeen",
  :name => "Jay Killeen",
  :role => "admin",
  :active => true,
  :created_at => Some Date,
  :updated_at => Some Date
}
$ user.zendesk
=> #<ZendeskAPI::Collection:0x007f04b4c26220 ... ... ...
```
from here, what would I do to get all the users tickets? When I try

```bash
[3] mk8 »  user.zendesk.tickets.count
I, [2015-03-18T15:44:55.193493 #17523]  INFO -- : get https://domain.zendesk.com/api/v2/users/search/tickets?query=admin%40domain.com
D, [2015-03-18T15:44:55.193904 #17523] DEBUG -- :   Accept: "application/json"
  Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
  User-Agent: "ZendeskAPI API 1.6.0"
I, [2015-03-18T15:44:56.478398 #17523]  INFO -- : Status 404
D, [2015-03-18T15:44:56.478759 #17523] DEBUG -- :   server: "nginx"
  date: "Wed, 18 Mar 2015 05:44:56 GMT"
  content-type: "application/json; charset=UTF-8"
  transfer-encoding: "chunked"
  connection: "close"
  status: "404 Not Found"
  x-zendesk-api-version: "v2"
  x-frame-options: "SAMEORIGIN"
  x-zendesk-origin-server: "app39.pod4.sac1.zdsys.com"
  x-ua-compatible: "IE=Edge,chrome=1"
  cache-control: "no-cache, private"
  x-request-id: "83bf5adb286e3037eb2d564e8d8776b8"
  x-runtime: "0.088944"
  x-rack-cache: "miss"
  x-zendesk-request-id: "6b5f0b945e85207daf0d"
  content-encoding: "gzip"
{"error"=>"InvalidEndpoint", "description"=>"Not found"}
=> -1
```

To give more info. I can run `rails console` again and try
```bash
Zendesk.client.tickets.count
...[ALL TICKETS GET RETURNED]
=> 2051
```

```bash
Zendesk.client.tickets.find(id: 1000)
I, [2015-03-18T15:48:40.561464 #17523]  INFO -- : get https://domain.zendesk.com/api/v2/tickets/1000
D, [2015-03-18T15:48:40.561675 #17523] DEBUG -- :   Accept: "application/json"
  Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
  User-Agent: "ZendeskAPI API 1.6.0"
I, [2015-03-18T15:48:41.672663 #17523]  INFO -- : Status 200
D, [2015-03-18T15:48:41.673284 #17523] DEBUG -- :   server: "nginx"
  date: "Wed, 18 Mar 2015 05:48:41 GMT"
  content-type: "application/json; charset=UTF-8"
  transfer-encoding: "chunked"
  connection: "close"
  status: "200 OK"
  x-zendesk-api-version: "v2"
  x-frame-options: "SAMEORIGIN"
  x-zendesk-origin-server: "app25.pod4.sac1.zdsys.com"
  x-ua-compatible: "IE=Edge,chrome=1"
  etag: "W/\"78ef874fe4\""
  cache-control: "must-revalidate, private, max-age=0"
  x-request-id: "ef4e4fe4e4f"
  x-runtime: "0.085837"
  x-rack-cache: "miss"
  x-zendesk-request-id: "231651561"
  x-content-type-options: "nosniff"
  content-encoding: "gzip"
{"ticket"=>{DETAILS}
=> #<ZendeskAPI::Ticket {DETAILS}>
```

This all looks pretty successful so far. Now I try to find all tickets by a search on the requested by user email and I get

```bash
[11] mk8 »  Zendesk.client.tickets.search(query: 'requested_by:admin@domain.com').fetch
I, [2015-03-18T15:52:14.557993 #17523]  INFO -- : get https://domain.zendesk.com/api/v2/tickets/search?query=requested_by%3Aadmin%domain.com
D, [2015-03-18T15:52:14.558257 #17523] DEBUG -- :   Accept: "application/json"
  Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
  User-Agent: "ZendeskAPI API 1.6.0"
I, [2015-03-18T15:52:15.788341 #17523]  INFO -- : Status 400
D, [2015-03-18T15:52:15.788708 #17523] DEBUG -- :   server: "nginx"
  date: "Wed, 18 Mar 2015 05:52:15 GMT"
  content-type: "application/json; charset=UTF-8"
  content-length: "141"
  connection: "close"
  status: "400 Bad Request"
  x-zendesk-api-version: "v2"
  x-zendesk-origin-server: "app38.pod4.sac1.zdsys.com"
  x-ua-compatible: "IE=Edge,chrome=1"
  cache-control: "no-cache, private"
  x-request-id: "dowjodijwn"
  x-runtime: "0.061831"
  x-rack-cache: "miss"
  x-zendesk-request-id: "feoihjeofjwkfn"
{"error"=>{"title"=>"Invalid attribute", "message"=>"You passed an invalid value for the id attribute. must be an integer"}}
=> []
```
It seems like most of these types of queries I am getting the same erorr back with `You passed an invalid value for the id attribute. must be an integer`.

It seems like in all the examples I have seen so far, you can query on users by attributes like email, but when it comes to tickets you need an id? Is this correct?

**Comment by cap3618** [comment]
I try zendeks.com. But they said that your
account has expired. How can I do?

Namsuncho
2015. 3. 18. 오후 2:57에 "Jay Killeen" <notifications@github.com>님이 작성:

**Comment by buheryfi** [comment]
Hi Jay,

I'm not much of a Rubyist, but I can tell you that api/v2/tickets/search is not a valid method.  There is no search method within the Tickets Endpoint.  The Search URL would look like /api/v2/search.json?query={search_string}, whereas the URL it is trying to access is api/v2/tickets/{id} - id should be an integer and obviously search is a string and not an integer.

Sincerely,
James Peterson

**Comment by jaykilleen** [comment]
Thanks. I understand that now that you've explained it as the ticket 'end point' . So by that method it appears you need and 'id'  of the ticket. Is there then a method attached to any endpoint that allows you to search and have the result return a collection of tickets that match that query?? 

At the end of the day I have two simple queries in  mind. 
1) Return all tickets where the ticket requested by email equals the users email in my app
2) Return all tickets where the ticket attribute 'customer id' equals the customer id from my app. 
then I can loop through the collection  and display on the users how view and the customer show view. 

thanks again for your explanation.

**Comment by jaykilleen** [comment]
so reading the API documentation on 'listing tickets'.

GET /api/v2/users/{user_id}/tickets/requested.json

I'll give 'user.tickets.requested' a try in the morning. 

Seems to also have a limit on returning 100 tickets.

**Comment by buheryfi** [comment]
Hi Jay,

I hadn't even thought about using that method, but it definitely sounds like a good option in your case.  I was just thinking of the search.json method in general, but it does not allow for use of the User ID. 

Most endpoints are restricted to 100 results per page.  If there are multiple pages returned, you will need to paginate through the results using the value for the "next_page" parameter that is returned.  The only exceptions to this 100 per page that I am aware of are the Incremental Tickets Endpoints, which can return 1000 results per page.  They only allow for searching by Unix Timestamp, so you would be unable to query with just a user ID for those.

Sincerely,
James Peterson
