### ISSUE TITLE
Handle retry-after header when receiving HTTP 429

### ISSUE THREAD

**Issue by Jerskouille** [zendesk/zendesk_api_client_rb#217]
Hi,

I think the client lacks a functionnality that would be very handy and would avoid spamming Zendesks server for nothing : when there is a call with an answer of 429 (Too Many Requests), right now it retries until it gets no error.
But since you have the `retry-after` header in the response which tells you how many seconds you need to wait, you could sleep for the amount of time in the `retry_after`.

Hope you will consider implementing this !

**Comment by ggrossman** [comment]
Hi @Jerskouille , there is code in the library to do this:

https://github.com/zendesk/zendesk_api_client_rb/blob/badba5b7fcd7ae628d5e9499ba946ab666d5fe28/lib/zendesk_api/middleware/request/retry.rb#L23

Have you observed it not working properly?

**Comment by Jerskouille** [comment]
Hi @ggrossman ,

I had this behaviour while trying to use the client in a bad way, but here is some simple code to reproduce the problem : 

```ruby
zendesk.ticket.incremental_export(0).all {|t|}
```

I know I shouldn't have called `all` on this collection, now I'm only fetching.

But still, since the code you pointed has been implemented in the middleware, shouldn't it handle the case properly ?

**Comment by steved** [comment]
Make sure the option is [explicitly set](https://github.com/zendesk/zendesk_api_client_rb/wiki/Configuration#options) on configuration. I'm also don't think it will retry the `start_time is too recent` error as we don't send back a Retry-After.

**Comment by Jerskouille** [comment]
Hi,

I feel really dumb right now to have missed this part in the documentation. Sorry for the inconvenience.
As for the error, I was really talking about 429, since you can only call the endpoint once per minute, not about the `start_time is too recent`.
Now that I have enabled this option, the retry is working perfectly fine.

Thanks !
