### ISSUE TITLE
Raise exceptions on API errors instead of returning empty collections

### ISSUE THREAD

**Issue by duncan-bayne** [zendesk/zendesk_api_client_rb#218]
Currently, API errors are indistinguishable from empty find results.  

First, I supply valid credentials and search for a non-existent external ID, and receive an empty collection.  This is expected and idiomatic:

```
irb(main):005:0* client = ZendeskAPI::Client.new do |conf|
irb(main):006:1*   conf.url = url
irb(main):007:1>   conf.username = my_email_address
irb(main):008:1>   conf.token = valid_token
irb(main):009:1> end
=> #<ZendeskAPI::Client:0x0055555c6365f8 ...>
irb(main):010:0>
irb(main):011:0* client.tickets(external_id: 'this should return an empty collection').empty?
=> true
```

However, if I supply *invalid* credentials and search for a non-existent external ID, I also receive an empty collection.  I'd expect this to raise some sort of exception:

```
irb(main):013:0* client = ZendeskAPI::Client.new do |conf|
irb(main):014:1*   conf.url = url
irb(main):015:1>   conf.username = my_email_address
irb(main):016:1>   conf.token = invalid_token
irb(main):017:1>   conf.logger = Logger.new(STDOUT)
irb(main):018:1> end
=> #<ZendeskAPI::Client:0x0055555bcf0f48 ...>
irb(main):019:0>
irb(main):020:0* client.tickets(external_id: 'this should raise an exception but it does not').empty?
get https://myapp.zendesk.com/api/v2/tickets?external_id=this+should+raise+an+exception+but+it+does+not
  Accept: "application/json"
  Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
  User-Agent: "ZendeskAPI API 1.6.0"
Status 401
  server: "nginx"
  date: "Mon, 23 Mar 2015 06:29:20 GMT"
  content-type: "application/json; charset=UTF-8"
  content-length: "37"
  connection: "close"
  status: "401 Unauthorized"
  www-authenticate: "Basic realm=\"Web Password\""
  x-zendesk-origin-server: "app11.pod4.sac1.zdsys.com"
  x-ua-compatible: "IE=Edge,chrome=1"
  cache-control: "no-cache, private"
  x-request-id: "de1c9c09-d9c0-4bf0-cb37-b8ca3a61d710"
  x-runtime: "0.045630"
  x-rack-cache: "miss"
  x-zendesk-request-id: "f09fcbe9c66783eea65f"
{"error"=>"Couldn't authenticate you"}
=> true
```

**Comment by buheryfi** [comment]
Hi Duncan,

I see that your request returned a "Status 401" when you entered the wrong credentials, which is the standard error message returned by Zendesk in that case.  Exceptions are more likely to be raised when there is an error on the Zendesk side processing your request, not because of invalid credentials.  Are you unable to see the 'status: "401 Unauthorized"' inside of your work-flow?

Sincerely,
James Peterson

**Comment by steved** [comment]
By default, collections are lazy loaded and just eat errors. Take a look at [this wiki page](https://github.com/zendesk/zendesk_api_client_rb/wiki/Errors) for more info, but in essence you'll need to use methods like `fetch!` or `to_a!`.

**Comment by duncan-bayne** [comment]
`to_a` fails silently.  With invalid credentials (logging stripped):

```
irb(main):010:0>tickets = client.tickets(external_id: 'external/id/1').to_a
=> []
```

It fails the same way when the network is unreachable.  With valid credentials but no network connection (logging included):

```
irb(main):029:0> client.tickets(external_id: 'external/id/1').to_a
get https://greensync.zendesk.com/api/v2/tickets?external_id=external%2Fid%2F1
  Accept: "application/json"
  Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
  User-Agent: "ZendeskAPI API 1.6.0"
=> []
```

This makes it quite tricky to write an integration that responds sensibly to such issues.

**Comment by duncan-bayne** [comment]
Ohhhh, never mind.  `to_a!` not `to_a`.  Yup, `to_a!` raises an exception; I still think that should be the only way of doing it though :smile:

**Comment by devangvdesai** [comment]
This helped me after digging through the API:

(Assuming invalid credentials)

      begin
        @client.tickets.find!(id: 1)
      rescue ZendeskAPI::Error::NetworkError => e
        @response = nil
        raise "error: #{e.response[:body]['error']} - status: #{e.response[:status]}"
      end
