### ISSUE TITLE
Comment Threading author_id return whitelist error 

### ISSUE THREAD

**Issue by wqsaali** [zendesk/zendesk_api_client_rb#222]
Hi Team,
Awesome Api, but unfortunately i am facing a small issue, scenario is when end user create ticket it works perfectly but on the same ticket when he reply or comment, it shows as message is send from the author i registered the API, 
by googling it, i found i need to add author_id with comment like
ticket.comment = {:value => "some message", :author_id => 1232} but it shows "Removed restricted keys ["author_id"] from parameters according to whitelist"
currently i am using trail version, is it due to trail version or i missed something?

**Comment by steved** [comment]
Hm, you should definitely be allowed to post comments with a different author_id. Can you send an email to api _at_ zendesk.com with more detailed information?

**Comment by wqsaali** [comment]
@steved thanks,
i have sent email to api at zendesk.com
