### ISSUE TITLE
date-parsing error for some agents

### ISSUE THREAD

**Issue by dj-hedgehog** [zendesk/zendesk_api_client_rb#224]
I'm trying to authenticate the current user and return a useable token. I used your example-code available here: https://developer.zendesk.com/blog/zendesk-api-ruby-client-and-oauth-example

Strangely this works for some agents but doesn't for others. It seems to be an issue with the date-format function as the following stacktrace suggests.
I'm German so could it be a Umlaut-related problem?
**EDIT**: We found out that the error occurs when the signature of an agent contains Umlauts (ä,ö,ü,ß)

```
/opt/rubies/ruby-2.1.4/lib/ruby/2.1.0/json/common.rb:155→ encode
/opt/rubies/ruby-2.1.4/lib/ruby/2.1.0/json/common.rb:155→ initialize
/opt/rubies/ruby-2.1.4/lib/ruby/2.1.0/json/common.rb:155→ new
/opt/rubies/ruby-2.1.4/lib/ruby/2.1.0/json/common.rb:155→ parse
zendesk_api-1.6.0/lib/zendesk_api/middleware/response/parse_json.rb:18→ on_complete
faraday-0.9.1/lib/faraday/response.rb:9→ block in call
faraday-0.9.1/lib/faraday/response.rb:57→ on_complete
faraday-0.9.1/lib/faraday/response.rb:8→ call
zendesk_api-1.6.0/lib/zendesk_api/middleware/response/parse_iso_dates.rb:11→ call
zendesk_api-1.6.0/lib/zendesk_api/middleware/response/logger.rb:20→ call
zendesk_api-1.6.0/lib/zendesk_api/middleware/response/callback.rb:14→ call
faraday-0.9.1/lib/faraday/response.rb:8→ call
zendesk_api-1.6.0/lib/zendesk_api/middleware/response/raise_error.rb:9→ call
faraday-0.9.1/lib/faraday/rack_builder.rb:139→ build_response
faraday-0.9.1/lib/faraday/connection.rb:377→ run_request
faraday-0.9.1/lib/faraday/connection.rb:140→ get
zendesk_api-1.6.0/lib/zendesk_api/actions.rb:104→ find!
zendesk_api-1.6.0/lib/zendesk_api/actions.rb:119→ find
zendesk_api-1.6.0/lib/zendesk_api/collection.rb:62→ block (2 levels) in <class:Collection>
zendesk_api-1.6.0/lib/zendesk_api/client.rb:56→ current_user
/var/app/current/app/controllers/oauth_controller.rb:201→ block in <class:OauthController>
```

**Comment by sandlerr** [comment]
Ruby's JSON parser fails to parse certain characters when running in an ASCII environment. Can you show the output of the `locale` and `uname -a` commands? On Ubuntu, a possible solution is to run your application with the following environment variable: `LANG=C.UTF-8`

**Comment by dj-hedgehog** [comment]
We found that it's directly related to the signature of a Zendesk-user. If it contains Umlauts (ä,ö,ü,ß) this error occurs.

Here are my `locale`settings:
```
LANG=de_DE.UTF-8
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

and this my `uname -a` output:

```
Linux ip-*-*-*-* 3.14.20-20.44.amzn1.x86_64 #1 SMP Mon Oct 6 22:52:46 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by steved** [comment]
Ruby 2.0 should have changed `Encoding.default_external` to UTF-8 by default. Can you confirm that this is still the case? I can reproduce your error by setting `Encoding.default_external = 'US-ASCII'` in my example script.

**Comment by MarkusHarmsen** [comment]
I can confirm the error. The default external encoding is UTF-8:
```
>> Encoding.default_external
=> #<Encoding:UTF-8>
```

**Comment by steved** [comment]
Can you try and check the encoding of the response body before the JSON parsing kicks in? It's very odd that your locales look alright and Ruby's settings are ok, but it still fails.

**Comment by steved** [comment]
Can you reproduce this outside of Rails btw?
