### ISSUE TITLE
"all" and "all!" can still enter infinite loop

### ISSUE THREAD

**Issue by P9GIT** [zendesk/zendesk_api_client_rb#227]
Hi Zendesk.

We are still experiencing an infinite loop in the "all!" method with version 1.7.1.
It happens if the client does not specify a per_page value whereby last_page? always returns false if there are more than one (default sized) page.
E.g. we have a two page group members list (using client.group_memberships.all!) where after page 2 is fetched, these values are set:
@options["page"] = 2
@options["next_page"] = nil
@options["per_page"] = nil
count = 129
making last_page? return false even though it IS the last page.

I realize that client.group_memberships.per_page(x).all! solves the issue, but this is a break from the previous way the all-iteration worked and is not mentioned in the docs.

Cheers,
Thomas.

**Comment by steved** [comment]
Can you see if https://github.com/zendesk/zendesk_api_client_rb/pull/229 works for you in all cases? Conceptually, it makes sense, but I can't recall why it was like that from the beginning and there are no tests :disappointed:

**Comment by P9GIT** [comment]
I can confirm that #229 solves the looping issue when just doing "client.group_memberships.all!" without setting per_page.
I haven't found any unwanted side effects either when going through our various cases.

I guess the Zendesk API server side next_page/previous_page feature can be relied on independently of the page size, so I think your solution is pretty solid and the way to go.

Thomas.

**Comment by steved** [comment]
Cool. I made sure #225 is still fixed and released as v1.7.3.

**Comment by P9GIT** [comment]
Great. Thanks! :o)
