### ISSUE TITLE
Some Ticket Data Missing

### ISSUE THREAD

**Issue by kumar-eligible** [zendesk/zendesk_api_client_rb#230]
Is it possible that for some tickets, some data in api response is missing? We were using version 1.3.6 When we created new ticket then do ticket.save and assign some attributes from ticket, it happens that sometimes we do not receive requester and other info.

Could you please confirm if this is possible?

ticket = ZendeskAPI::Ticket.new(
      client,
      requester_id: ..,
      priority: ...,
      type: ..,
      subject: ..,
      description: ..,
      tags: ...
    )

if ticket.save
   assign values (Sometimes some values are missing in ticket)
end

**Comment by steved** [comment]
Can you be more specific with which data is missing from the ticket response? We should be returning the exact same data as `GET /api/v2/tickets/:id`.

**Comment by kumar-eligible** [comment]
Some tickets missed data such as requester_id, type, description.

**Comment by steved** [comment]
Is this reproducible? If you have a specific example, but can't share it, email "api@zendesk.com" and we'll take a look further.

**Comment by kumar-eligible** [comment]
I can't reproduce it on local, but it's constantly happening on prod. What all info do you need to check this?

**Comment by steved** [comment]
Do you know if this is specifically an API client bug? Is the response data from the request actually valid?

**Comment by kumar-eligible** [comment]
How do you check if the response is valid?
One thing i noticed that the tickets that were missing data have status as "New' and priority as 'Normal' while other tickets have status as 'new' and priority as 'normal'. (I.e. titleized)

**Comment by steved** [comment]
If you [turn on logging](https://github.com/zendesk/zendesk_api_client_rb/wiki/Configuration#options) you can see the full response body.

**Comment by kumar-eligible** [comment]
seems like issue is on our end only.
We use 
zendesk_client.ticket.incremental_export(from_timestamp).to_a
endpoint to sync our db but this endpoint does not provide all the fields e.g. requester_id, description etc.

Could you please let me know if you have any other such end-point which could be used to get all the changes along with all the fields. 

Sorry for all the trouble and thanks for all the help.
