### ISSUE TITLE
Unable to track ".changed?" for arrays

### ISSUE THREAD

**Issue by mathielo** [zendesk/zendesk_api_client_rb#233]
_What follows is just an example to illustrate my current situation. All requests shown as examples were actually made._

Creating users with tags worked fine:

```
client.users.create(email: "john@example.com", name: "John Example", verified: true, tags: ["first_tag", "second_tag"])
```

`Logger`'s output:

```
I, [2015-05-21 14:29:40#44533]  INFO -- : post https://xxx.zendesk.com/api/v2/users
D, [2015-05-21 14:29:40#44533] DEBUG -- :   Accept: "application/json"
    Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
    User-Agent: "ZendeskAPI API 1.7.4"
{"user"=>#<Hashie::Mash email="john@example.com" name="John Example" tags=["first_tag", "second_tag"] verified=true>}
I, [2015-05-21 14:29:41#44533]  INFO -- : Status 201
```

A end-user called _John Example_ was successfully created in my Sandbox with both tags. Later on, I tried to update John. Every field was updated, except for the **tags**.

```
john = client.users.search(query: "john@example.com").first
john.name += " updated"
john.tags.push("third_tag")
john.alias = "jexmpl"
john.save
```

Checking again on Zendesk John now is _John Example updated_, it has the "jexmpl" alias but the tags remain the first two that were set upon creation, and `third_tag` was not added.

Checking `Logger`'s outputs, I've noticed that the client's `PUT` request only sends the **updated** (a.k.a. **changed**) fields to Zendesk API. 

```
I, [2015-05-21 14:35:26#46888]  INFO -- : put https://xxx.zendesk.com/api/v2/users/984876129.json
D, [2015-05-21 14:35:26#46888] DEBUG -- :   Accept: "application/json"
  Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
  User-Agent: "ZendeskAPI API 1.7.4"
{"user"=>#<Hashie::Mash alias="jexmpl" name="John Example updated">}
I, [2015-05-21 14:35:27#46888]  INFO -- : Status 200
D, [2015-05-21 14:35:27#46888] DEBUG -- :   server: "nginx"
```

Notice that only `alias` and `name` where send, while `tags` was left aside. The client didn't understand that `tags` attribute had changes, so it was left out of the `PUT` request.

Digging into the Gem's code, I've found out that the problem lies within the `changes` method in [lib/zendesk_api/track_chages.rb](https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/track_changes.rb#L62). The `tags` attribute validates at the first check on line 67 (`v.is_a?(Array)`) but fails when checked upon `v.any? {|val| val.respond_to?(:changed?) && val.changed?}`.

That was the farthest I went. Unfortunately I don't actually know how to fix it, otherwise I'd be sending a pull request instead of opening an issue. 

---

Additional information: on another test, if I set `tags` as a comma-separated **string**, the client track the change and sends the attribute in the `PUT` request. While this might work as a workaround, it would be better to work with `tags` as an array.

Let me know if I can help somehow!

**Comment by steved** [comment]
Yes, unfortunately this has been a [caveat](https://github.com/zendesk/zendesk_api_client_rb#caveats) for a while. I still haven't figured out a good way to fix it without injecting into the broader array class. Since, this has really only been a problem with a select few fields perhaps a small shim would work.

**Comment by mathielo** [comment]
Ops, my bad! Didn't see that on the caveats section. Thanks for the reply @steved . 

Even tough it only affects only a few things, I believe `tags` to be an important one. I'll be looking for a solution as well and will PR if I find any suitable solution.
