### ISSUE TITLE
Ticket creation fails silently if the user is unable to create tickets due to expired password

### ISSUE THREAD

**Issue by benilovj** [zendesk/zendesk_api_client_rb#234]
The `client.ticket.create!(options)` method fails silently if the API user being used to create tickets has an expired password (ie if the user that talks to the API is an agent and the security settings for agents has a password expiry strategy).

When I investigated this, I saw that the API returns a status code `302` with body `You are being redirected to /password`. However the `create!` method doesn't raise any exception. The client really should catch this case.

**Comment by steved** [comment]
This appears to be a general API issue as it should return an error status. I'll update when it is fixed server-side.

**Comment by steved** [comment]
Unfortunately, an incident occurred during that time that affected token API requests for users without a  password set. Since it was not a valid JSON response, the client could not handle it properly. If a public postmortem is posted, I'll make sure to update here.

**Comment by benilovj** [comment]
Steve, does that mean that in future, the client will raise an exception when the user's account needs a password change?

**Comment by steved** [comment]
That specific error shouldn't happen again, password expiry has no affect on API token access. But actually maybe the client should consider 300s an invalid response. Let me look into it.

**Comment by steved** [comment]
I merged #236 so this specific type of issue (invalid responses being swallowed) shouldn't happen again without raising an exception.

**Comment by benilovj** [comment]
:+1: thanks
