### ISSUE TITLE
Parse data back into my app?

### ISSUE THREAD

**Issue by gregblass** [zendesk/zendesk_api_client_rb#241]
I have my own homegrown ticketing system in my rails app. I was able to use this gem to create and update tickets in zendesk when they are created in my app.

How would I go the other way? Like, lets say a user opens a ticket, and then I respond from within zendesk. How could I get it back into my app to keep everything synced up?

**Comment by steved** [comment]
You would probably want to poll the incremental ticket updates endpoint.
The documentation is here: https://developer.zendesk.com/rest_api/docs/core/incremental_export

I believe there is also a beta for HTTP targets which you can use to post-back to your application. But you may need to email api@zendesk.com for more information.

**Comment by aphundt** [comment]
Here is a summary of the solution provided:

I believe what you're trying to do can be accomplished through our apps ecosystem.

Here is a link to the full documentation for this: https://developer.zendesk.com/apps/docs/agent/introduction

Essentially you would make an event listener in the app to fire on an agent reply from within Zendesk and send the comment as a XHR back into your app.
