### ISSUE TITLE
zendesk_api is ssl only

### ISSUE THREAD

**Issue by trekr5** [zendesk/zendesk_api_client_rb#244]
Hello,

I've downloaded the zendesk_api_client ruby gem and attempted to connect to the ZenDesk API with the following configuration:-

    client = ZendeskAPI::Client.new do |config|
    config_url = "https://myorg.zendesk.com/api/v2"
    config.username = "admin@myorg.com"
    config.token = "MYTOKEN"
    require 'logger'
    config.logger = Logger.new(STDOUT)
    end

However I get the following error when I try to connect to the API:
ArgumentError: zendesk_api is ssl only; url must begin with https://

Can you please tell me what I'm doing wrong?

Thanks

**Comment by steved** [comment]
Just a typo, I think. Instead of `config_url =`, you should do `config.url =`.
