### ISSUE TITLE
Config issues.

### ISSUE THREAD

**Issue by samarthsikotara** [zendesk/zendesk_api_client_rb#247]
Where can I add configuration details?

**Comment by steved** [comment]
Are you referring to client configuration? Take a look at the [documentation](https://github.com/zendesk/zendesk_api_client_rb#configuration). Otherwise, can you be more specific?

**Comment by samarthsikotara** [comment]
Thanks for your reply. I've solved this problem. :)

**Comment by samarthsikotara** [comment]
Is there any caching mechanism for zendesk tickets? as every time I refresh my tickets page it hits api calls. so I need to control over it.

**Comment by steved** [comment]
Yes, but it's only in memory by default. If you point it to the Rails.cache, it should persist.
https://github.com/zendesk/zendesk_api_client_rb/wiki/Caching
