### ISSUE TITLE
Cant set default membership 

### ISSUE THREAD

**Issue by Wiwun** [zendesk/zendesk_api_client_rb#257]
The following code on version 1.11.1 of the ruby gem give a 500 error, 
we cant set a default membership with the ruby gem.

client = ZendeskService.create_client

ginnne_pig = client.users.first
default_org =  client.organizations.search(:external_id => 0).first
zendesk_membership = ZendeskAPI::OrganizationMembership.new(client, {:user_id => ginnne_pig.zendesk_id , :organization_id => default_org.id, :default => true})

begin
zendesk_membership.save!
rescue exception => e
  puts e.message
end

output:
the server responded with status 500

However the REST api documentation suggest it would be possible.
see:  https://developer.zendesk.com/rest_api/docs/core/organization_memberships#set-membership-as-default

How can we atcheive that with the Ruby Gem api?

Thanks,

**Comment by HashNuke** [comment]
@Wiwun The `zendesk_membership` assignment line refers to `ginnne_pid.zendesk_id`. The user object has no `zendesk_id` attribute. Use the `id` attribute instead.

```
client = ZendeskService.create_client

user = client.users.first
organization = client.organizations.search(external_id: 0).first
membership_params = {
  user_id: user.id,  # NOTE the use of id attribute instead of zendesk_id
  organization_id: organization.id,
  default: true
}
membership = ZendeskAPI::OrganizationMembership.new(client, membership_params)
membership.save!
```
