### ISSUE TITLE
client.organization.all dont support pagination.

### ISSUE THREAD

**Issue by Wiwun** [zendesk/zendesk_api_client_rb#258]
the following line will iterate only 100 times on organizations even if there is more:

client.organizations.all { | org |  puts "#{org.id}"}

In the doc it stipulate that all handle automatically the pagination.

Regards,

Louis-Rene

**Comment by steved** [comment]
This should work, I don't have any test accounts with that much data. Do you have any logs?

**Comment by Wiwun** [comment]
Might have something to do with deleting the organization in a
client.oganizations.all {} loop.
Or asynchronous mechanism on zendesk but you can reproduce it with the
small test ruby script I just wrote, See attachment files.

If you remove the org.destroy in the all loop, it does print all the
organizations.
If not, It stop to 100 and leave 25 org on the sanbox.

Regards,

Louis-Rene

2015-08-10 13:51 GMT-04:00 Steven Davidovitz <notifications@github.com>:

**Comment by Wiwun** [comment]
ruby script to reproduce  Warning, It delete all organizations using clients.organizations.all:
client = ZendeskService.create_client

i = 0
125.times do
    i=i+1
    puts "creating org_nb#{i}"
    org = ZendeskAPI::Organization.new(client, {:name => "org_nb#{i}" })
    org.save!
end

puts "Organization size: #{client.organizations.size}"

i=0
client.organizations.all { |o|
   puts o.name
   i = i +1
   puts "destroying #{o.name}"
   o.destroy!
}

puts "total iterations = #{i}"

puts "Organization size: #{client.organizations.size}"

**Comment by steved** [comment]
Ah, right. It'll try to grab page two, but you've already deleted the first 100 so that's now page one. I would collect them first, then destroy them after.
