### ISSUE TITLE
Trying to find First Reply Time data

### ISSUE THREAD

**Issue by trekr5** [zendesk/zendesk_api_client_rb#259]
Hello,

I'm new to the ZenDesk API and am trying to find First Reply Time data. 

I have gone through the documentation and can't see where this is referenced. 

Can you tell me if First Reply Time is an endpoint in the API or if not how I can find it?

Many thanks

**Comment by steved** [comment]
Yep, you should be able to find the reply time inside the [ticket metrics](https://developer.zendesk.com/rest_api/docs/core/ticket_metrics) endpoint.

Using the api client:
```ruby
ZendeskAPI::Ticket.new(client, id: X).metrics.reply_time_in_minutes
```
