### ISSUE TITLE
Updating user email creates a new identity

### ISSUE THREAD

**Issue by ldallas** [zendesk/zendesk_api_client_rb#261]
Hi, not sure if that's the right place to ask such a question, but updating user email creates a new secondary identity instead of changing the primary one, at least that would be expected behaviour. 
```
user = client.users.first
user.update(email: "new@email.com")
user.save!
```
Thanks.

**Comment by steved** [comment]
Currently, you can only update user identities through the user identity update API.

Something like should work:

```ruby
user = client.users.first
id = user.identities.first # or user.identities.detect {|id| id.value == ...}
id.value = 'example@example.org'
id.save!
```
