### ISSUE TITLE
Tags on Organization vs. Users

### ISSUE THREAD

**Issue by 3en** [zendesk/zendesk_api_client_rb#263]
> users.find(:id=>{ID}).tags.class
> => Array

-

> organization.find(:id=>{ID}).tags.class
> =>  ZendeskAPI::Collection

Out of curiosity is there any thinking / reasoning behind why calling tags for users and organizations return different objects?

**Comment by steved** [comment]
Nope, just an oversight. Released 1.11.5 as a fix.
