### ISSUE TITLE
Detect best locale for requester when creating ticket

### ISSUE THREAD

**Issue by muaad** [zendesk/zendesk_api_client_rb#267]
We are creating tickets like this:

`requester = ZendeskAPI::User.create(client, { name: "John", phone: "1234567890" })
ZendeskAPI::Ticket.create(client, :subject => "subject", :comment => { :value => "This is a comment" }, :submitter_id => requester.id, :requester_id => requester.id)`

I am told Zendesk can auto-detect the ticket's language and set the requester's locale based on that.

Is there a way I can do that with this gem?

Thanks.

**Comment by steved** [comment]
Hi, this currently isn't possible in the gem and in our API. However, it's definitely an interesting idea. I've created a request in our system to track it.

**Comment by AsWali** [comment]
Any updates on this ?
