### ISSUE TITLE
No way to remove item from custom_field_options dropdown array

### ISSUE THREAD

**Issue by kylefurlong** [zendesk/zendesk_api_client_rb#268]
As title. I can add a Trackie to this array and add a new option, but no technique I have tried to delete the same has worked. Removing the item from the array on the resource, and calling save does not send the proper json.

**Comment by steved** [comment]
Can you provide an example? Is it because the object isn't changed?

**Comment by Meldryn** [comment]
component_ticket_field = zendesk_api.ticket_fields.find(:id
=> @ticket_field_id)
                deletee = nil
                component_ticket_field.attributes.custom_field_options.each
do |option|
                    if option.name == @name
                        deletee = option
                    end
                end
                if !deletee.nil?
                    # This looks strange because the Zendesk API library
                    # does not "track" changes to arrays within the
attributes
                    # of resources. The 'attributes' field does track coarse
                    # updates to its keys, so setting 'custom_field_options'
                    # to nil, then to a new array triggers the change logic,
                    # and sends the correct put request when calling save
                    saved_options =
component_ticket_field.attributes['custom_field_options'].dup

component_ticket_field.attributes['custom_field_options'] = nil
                    saved_options.delete(deletee)

component_ticket_field.attributes['custom_field_options'] = saved_options
                    component_ticket_field.save

**Comment by nogates** [comment]
As mentioned in the caveats section, modifying arrays doesn't update resources directly: https://github.com/zendesk/zendesk_api_client_rb#caveats
