### ISSUE TITLE
membership list for organization?

### ISSUE THREAD

**Issue by jademcgough** [zendesk/zendesk_api_client_rb#269]
The (non-ruby) API docs specify an endpoint for viewing the membership of a given organization:

`GET /api/v2/organizations/{organization_id}/organization_memberships.json`
(https://developer.zendesk.com/rest_api/docs/core/organization_memberships#list-memberships)

I can seemingly do this through the ruby client like so:
```
org = client.organization.find(id: SOME_ORG_ID)
org.users.fetch
```

But this requires two API requests, when it should only require one. Is this endpoint missing from the ruby client?

**Comment by steved** [comment]
You can initialize an organization object without trying to "find" it first, if you already know the id. So this will do one request:

```
org = ZendeskAPI::Organization.new(client, id: ORG_ID)
org.users.fetch
```

**Comment by jademcgough** [comment]
Ah, thank you!
