### ISSUE TITLE
public false is not working!

### ISSUE THREAD

**Issue by samarthsikotara** [zendesk/zendesk_api_client_rb#270]
I want to create a ticket on behalf of a user but i don't want to acknowledge the user about it.

I tried creating a internal ticket comment using set public to false it creates as public mode not in private mode..
<pre>
ZendeskAPI::Ticket.create(zendesk_client, :subject => ".....", :type => 'task', :status => 'new', :requester => { :email => BOB@BOB.COM., :name => "BOB" }, :comment => {:body => Hello, :public => false}, :priority => "urgent")
</pre>

**Comment by steved** [comment]
As far as I know, private first comments are not supported by the API. Please open a ticket with support@zendesk.com and someone may be able to help you with a solution.

**Comment by buheryfi** [comment]
Hey dudes, just tried this via cURL and the first comment came out private, so it is supported by API.  Might want to revisit this one if @samarthsikotara is still not able to accomplish it with this client.

**Comment by steved** [comment]
Yeah, it seems to work fine. @samarthsikotara can you confirm or open shoot an email to `api@zendesk.com` so we can get into more detail?

**Comment by samarthsikotara** [comment]
Hey @steved It's working fine now.
