### ISSUE TITLE
Bulk importing users

### ISSUE THREAD

**Issue by conorhynesire** [zendesk/zendesk_api_client_rb#274]
Is it possible to add functionality to bulk import users using this api?

https://developer.zendesk.com/rest_api/docs/core/users#create-many-users

From what I can see, the change would mean extending create many into the users class?

Or is there an alternate way to accomplish this?

**Comment by steved** [comment]
Yep, that's it. Added 0c28217 and released v1.12.1. You can use it like `client.users.create_many!` or `ZendeskAPI::User.create_many!`.
