### ISSUE TITLE
User Search Sometimes Returns Empty Even When Records Exist

### ISSUE THREAD

**Issue by muaad** [zendesk/zendesk_api_client_rb#275]
We have an integration with Zendesk where we create tickets from WhatsApp messages automatically so we use phone numbers to identify users.

When we receive a WhatsApp message, we search Zendesk for a user with that number. If we find one, we use it as the requester of the new ticket or the author of the comment and if we don't find any, we create a new user.

Basically, we have a `find_or_create_by_phone_number` method that is made up of these two methods:

``` ruby
def find_user_by_phone_number phone_number
    client.users.search(query: phone_number).first
end
```

And

``` ruby
def find_or_create_user_by_phone_number name, phone_number
    user = find_user_by_phone_number(phone_number)
    if user.nil?
      user = ZendeskAPI::User.create(client, { name: name, phone: phone_number })
    end
    user
end
```

Recently, we have found that many user records were being created on Zendesk for the same phone number. Excuse the title as that may not be the cause, but, since we only create new users if we don't find a user record for a phone number, the search must be returning an empty array sometimes even when records exist for that phone number. I say sometimes because I haven't been able to reproduce this issue on the console.

Also, the results of the search seem to be sorted randomly as `client.users.search(query: phone_number).first` returns different records at different times. This has resulted in having different comment authors in the same ticket.

It is getting kind of confusing. Please help clarify.

Thanks.

**Comment by steved** [comment]
There is definitely a delay in search indexing, this is unavoidable. How about using the phone number as an external id as well? This would validate uniqueness as well as being directly accessible by using `client.users.search(external_id: ...).first`.
