### ISSUE TITLE
exports/{resource} API being deprecated

### ISSUE THREAD

**Issue by carlesjove** [zendesk/zendesk_api_client_rb#276]
Hello,

This is more of a question. I'm working on an integration with Zendesk, and using `Ticket.incremental_export`. Currently, this method is calling `exports/tickets`, instead of `incremental/tickets`, as the [specs document](https://github.com/zendesk/zendesk_api_client_rb/blob/e4a74b86b2f62ef639e516ee66e666670d15c0dc/spec/live/ticket_spec.rb#L57).

According to Maxime from Zendesk (replying to [this question](https://support.zendesk.com/hc/en-us/articles/204396193-New-Incremental-APIs-now-available-to-all-accounts#comment_202511566)), the `exports/` API is to be deprecated soon. Are there plans to use the new `incremental` API for Tickets in an upcoming version?

Thanks.

**Comment by ggrossman** [comment]
Fixed by merging https://github.com/zendesk/zendesk_api_client_rb/pull/381
