### ISSUE TITLE
How to get a list of a specific users requested tickets? 

### ISSUE THREAD

**Issue by kmandeville** [zendesk/zendesk_api_client_rb#289]
I can't seem to figure out how to do the following API request with this gem: 

/api/v2/users/<userId>/tickets/requested.json

I've tried doing a client.search(:query => "type:ticket requested_id: #{@user.id}")  

That ends up creating the following API call: 

/api/v2/search?query=type%3Aticket+requested_id%3A+<userId>

And it returns nothing. This doesn't seem to work through the API as I get nothing in return. I'm trying this against a free trial account. Is it possible that this is a limitation in the level of my account?

**Comment by steved** [comment]
You can do `ZendeskAPI::User.new(client, id: @user.id).requested_tickets`

**Comment by kmandeville** [comment]
Thank you so much. That's the one thing I did not try!
