### ISSUE TITLE
client.users.all returns in 1 of 15 cases not all entries

### ISSUE THREAD

**Issue by thorsteneckel** [zendesk/zendesk_api_client_rb#290]
I have an issue when fetching all Users via client.users.all. My tests showed that in ~1 of 15 cases there are less Users returned than existing. For example you have 137 Users in your Zendesk system and when fetching them via client.users.all only 37 get returned. This is very strange and not consist reproducible. I couldn't track it down in the code yet. So I can't say if it's caused by the Gem or the API endpoint.

Is there any known issue?

Feedback would be great! It's kinda urgent.

**Comment by thorsteneckel** [comment]
I managed to debug my way through the Gem and found the following response genereated here:
https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/collection.rb#L400

Response:
```
...
\"next_page\"=>nil, \"previous_page\"=>\"https://xxx.zendesk.com/api/v2/users.json?page=1\", \"count\"=>137} @url=#<URI::HTTPS https://xxx.zendesk.com/api/v2/users?page=2>
...
```
From my understanding the API (requests) work as they should. But since only 37 of the 137 Users are processed in the block and the API returns 100 records each request it seems to me the block is not executed for the first 100 entities. I veified this and my logs showed that the block is not executed for the first 100 entities. If my schedule allows it I will dig deeper and try to understand what could have prevented the block execution and not throwing an error.

**Comment by sandlerr** [comment]
@thorsteneckel could you share a code snippet that demonstrates this behaviour?

**Comment by sandlerr** [comment]
You may also consider the bang method: `client.users.all!` this way you're more likely to see an error in the logs.

**Comment by thorsteneckel** [comment]
Hi @sandlerr - thanks for your feedback. It was possible to reproduce this with the following simple lines:

```ruby
zendesk_users = []
client.users.all { |zendesk_user|
  zendesk_users.push(zendesk_user)
}

if zendesk_users.size != 137
  p zendek_users.size
  p zendesk_users
end
```

I replaced `.all` by `.all!` but wasn't able to reproduce it back then. I'll try to look into this later this day again.

**Comment by nogates** [comment]
Gonna close this since it's a very long issue and `all!` seemed to work just fine 🤷‍♂
