### ISSUE TITLE
Comment value corresponds to which attribute of a comment?

### ISSUE THREAD

**Issue by peyterkim** [zendesk/zendesk_api_client_rb#292]
In the Zendesk Core API, comments have attributes "body" and "html_body".
I'm assuming this gem passes in "body" because when I go to Zendesk's platform to view a ticket, the comments are not html formatted, displaying tags such as `<p>` and whatnot.
Is there any way we can address html formatted comments?
![screen shot 2016-02-24 at 1 57 24 pm](https://cloud.githubusercontent.com/assets/5760340/13297092/9142066a-dafe-11e5-92b0-2520d9e32715.png)

**Comment by steved** [comment]
Yes, "value" and "body" are the plaintext body. You can set html_body and it will show up properly.
