### ISSUE TITLE
Can't upload/attach a file to ticket

### ISSUE THREAD

**Issue by blakeprudhomme** [zendesk/zendesk_api_client_rb#296]
I am getting the following error when trying to send an attachment via a `<%= file_field_tag :attachment, class: "file" %>` with a ticket.

``` ruby
@ticket = WatchmanZendesk.ticket.new(
  subject: params[:subject],
  comment: "#{current_user.full_name} asked the following question:\n\n#{params[:body]}\n\n#{@result.support_notes}",
  requester: { name: account_manager.full_name, email: account_manager.email },
  tags: ["platform-#{@result.computer.platform}"],
  custom_fields: [
    { id: browser_details, value: params[:browser_details] },
    { id: urgent, value: params[:urgent].present? ? "sr_urgent" : "in_app_report" }
  ]
)
@ticket.comment.uploads << params[:attachment]
@ticket.save
```

gives me 

``` bash
undefined method `<<' for nil:NilClass
```

I cannot seem to debug it. 

Rails 4.2.5
Ruby 2.1.8
zendesk_api_client_rb v1.13.4

**Comment by tuckyeah** [comment]
Was there any resolution on this? I'm getting the same error.

**Comment by blakeprudhomme** [comment]
@tuckyeah There was an issue calling `ticket` on `ZendeskAPI::Client.new` like`WatchmanZendesk.ticket.new` in my original example where
`WatchmanZendesk = ZendeskAPI::Client.new`

After a chat with Zendesk support it was recommended to me to instead use `ZendeskAPI::Ticket`
and pass `ZendeskAPI::Client.new` as the first arg

so my above code changed to 

```ruby
@ticket = WatchmanZendeskTicket.new(
  WatchmanZendesk,
  subject: subject,
  comment: comment,
  requester: requester,
)
@ticket.comment.uploads << params[:help_attachment]
@ticket.save!
```

where `WatchmanZendeskTicket = ZendeskAPI::Ticket`
and `WatchmanZendesk = WatchmanZendesk = ZendeskAPI::Client.new do |config|...`


Hope that is clear.

**Comment by tuckyeah** [comment]
@blakeprudhomme huge help! that solved it :) thank you so much for your quick response!!
