### ISSUE TITLE
{"error"=>"invalid_token", "error_description"=>"The access token provided is expired, revoked, malformed or invalid for other reasons."}

### ISSUE THREAD

**Issue by Haseeb717** [zendesk/zendesk_api_client_rb#297]
{"error"=>"invalid_token", "error_description"=>"The access token provided is expired, revoked, malformed or invalid for other reasons."}

**Comment by Borisstoy** [comment]
Getting the same error here. Anyone?

**Comment by NicolasMeseguer** [comment]
Same here,. no idea why !

**Comment by joao-dantas** [comment]
Same here.

**Comment by huynhdungbk11** [comment]
Anyone?

**Comment by huynhdungbk11** [comment]
Just remove 
config.access_token = 'xxx'
check this code below:
[code]
client = ZendeskAPI::Client.new do |config|
  config.url = 'https://xxx.zendesk.com/api/v2'
  config.username = 'xxx@xxx'
  config.token = 'xxxx'
  config.retry = true
end
[/code]
