### ISSUE TITLE
Automatically retry a call when a 409 conflict status is raised

### ISSUE THREAD

**Issue by donflannagan** [zendesk/zendesk_api_client_rb#305]
The client needs to retry a call when a 409 conflict status is raised.  Currently there is retry logic in the client gem and it would simplify the caller by having the retry catch this status as well.

**Comment by nogates** [comment]
@donflannagan, sorry for the late reply. We are gonna close this since we understand that there are ways for clients to implement retry when server returns 409, but maybe not all of them are interested in doing that
