### ISSUE TITLE
Is there a way to hit /users/create_or_update with this gem?

### ISSUE THREAD

**Issue by magni-** [zendesk/zendesk_api_client_rb#308]
https://developer.zendesk.com/rest_api/docs/core/users#create-or-update-user

I'm not seeing anything related to it in the code or in the docs.

``` ruby
client.users.create_or_update(name: 'foo', email: 'bar@baz.com')
# doesn't seem to do anything

ZendeskAPI::User.create_or_update(client, {name: 'foo', email: 'bar@baz.com'})
# NoMethodError: undefined method `create_or_update' for ZendeskAPI::User:Class
```

Am I missing something obvious, or is the functionality not there?

**Comment by geo1004** [comment]
You can do it in this way : 

`ZendeskAPI::User.create(client, email: object_email, name: object_name)`

If you use zendesk_rails and you have initialized the client, you can replace 'client' by : 

`ZendeskRails.client`

**Comment by magni-** [comment]
That clearly doesn't work:
```ruby
client.users.create!(name: 'Duplicate User', email: 'duplicate@user.com')
=> ZendeskAPI::Error::RecordInvalid: ZendeskAPI::Error::RecordInvalid: {"email"=>[{"description"=>"Email: duplicate@email.com is already being used by another user", "error"=>"DuplicateValue"}]}
```

**Comment by magni-** [comment]
Here's how I ended up doing it, for those brought here by Google:
```ruby
response = client.connection.post(
  '/api/v2/users/create_or_update.json', 
  {user: {email: EMAIL, name: NAME}},
)
ZendeskAPI::User.new_from_response(client, response)
```

**Comment by maxkwallace** [comment]
I had to reimplement this in my code as well-- couldn't figure out a way to do it via the API client.

**Comment by jaxn** [comment]
Leave off the `!`

Found this via Google and @geo1004 gave the correct answer.

**Comment by Derekbrenner** [comment]
It would be nice to have the create_or_update call as well.

**Comment by hkmaly** [comment]
Any progress on this?

**Comment by hkmaly** [comment]
Note that I tried the #360 and it doesn't seem to work ; specifically, there should be singular_resource_name instead of resource_name and Collection class also needs to be modified.

**Comment by josephsiefers** [comment]
I agree with @hkmaly - #360 misses the mark. It should be `singular_resource_name` [here](https://github.com/zendesk/zendesk_api_client_rb/blob/73a068a63de384c0c66c446b1a234469928254a5/lib/zendesk_api/actions.rb#L190). 

I receive the following error:
```WARNING: Removed restricted keys ["users.email", "users.name"] from parameters according to whitelist```
which demonstrates it should be singular.

**Comment by petrachi** [comment]
Yes, I have the same problem with singularized resource name. 
This code : 
`
ZendeskAPI::User.create_or_update!(client,
  external_id: 34,
  name: 'yoyo-r',
  verified: true,
)
`
Generates these params : `{"users"=>{:external_id=>34, :name=>"yoyo-r", :verified=>true}}`
It should be : `{"user"=>{:external_id=>34, :name=>"yoyo-r", :verified=>true}}`

**Comment by nogates** [comment]
@petrachi @josephsiefers Created a fix for this on https://github.com/zendesk/zendesk_api_client_rb/pull/404. Thanks for reporting this!
