### ISSUE TITLE
Couldn't I set type of ticket? 

### ISSUE THREAD

**Issue by jsnick** [zendesk/zendesk_api_client_rb#311]
I cannot set the type of ticket while creating a ticket.
(default "incident", but I want to change the value to "question")

```ruby
test_ticket_data = { 
  type: "question",                                                                                                                                                                  
  brand_id: bv,
  ticket_form_id: valid_ticket_form_id,                                                                                                                                                            
  requester: { 
    locale_id: valid_locale_id,
    email: "my@email",                                                                                                                                                 
    name: "dummy name",                                                                                                                                                          
  },
  subject: "dummy subject #{SecureRandom.hex(2)}",                                                                                                                     
  comment: {
    body: "dummy content #{SecureRandom.hex(4)}"                                                                                                                                 
  },                                                                                                                                                                             
}
zc = ZendeskService.new.client # ZendeskService is ZendeskAPI::Client wrapper.
zc.tickets.create!(test_ticket_data) # no error, no warning, and success to create real ticket.
```

After created, the type of this ticket created by above code is default value of type, "incident"

Is this bug ? or Did I something wrong ?  
[API documentation](https://developer.zendesk.com/rest_api/docs/core/tickets#json-format) says `:type` field is not read-only

**Comment by lpopa** [comment]
I am experiencing the same issue with `:type` plus some other attributes like `:due_at`. Interesting enough, issuing creation with the params for a ticket behaves as expected in Sandbox.

Based on the error I got when trying to call `save!` from console( `WARNING: Removed restricted keys ["due_at", "attributes"] from parameters according to whitelist`), I think that version 2 of the API for production has a different list of permitted params(not consistent with [API documentation](https://developer.zendesk.com/rest_api/docs/core/tickets#create-ticket) ).

**Comment by lpopa** [comment]
I've opened a ticket with support and learned that if your field is inactive, you won't be able to set it([ticket fields](https://support.zendesk.com/hc/en-us/articles/203661506-About-ticket-fields)).

To check your settings: Admin Panel >> Manage >> Ticket Fields. At the bottom of the page you will find all the fields that are inactive. 

Hope this will solve your problem.

**Comment by jsnick** [comment]
@lpopa Thank you for answering.
I don't know what the relation is with `:type` of a ticket and active/inactive status of a ticket field.
Anyway, my test ticket form includes only default 5 fields. (title, description, status, group, agent)
and those are all active.
Still I couldn't change `:type` of a ticket!!

**Comment by lpopa** [comment]
In order to set that field(your case `:type`) you need to make sure that in the Admin that it is an active ticket field.  From the page I linked you before:

> Note: If you deactivate the Type field, all of your tickets will default to Incident.

**Comment by jsnick** [comment]
Oh, There is a :type system field in deactivation zone. 
Thank you!
It works well after activate it.
