### ISSUE TITLE
Ticket bulk import?

### ISSUE THREAD

**Issue by mwpastore** [zendesk/zendesk_api_client_rb#314]
I'm trying to access the [ticket bulk import](https://developer.zendesk.com/rest_api/docs/core/ticket_import#ticket-bulk-import) feature. I've tried numerous variations on the following without much luck:

``` ruby
client.tickets.create_many!(my_tickets, :path => 'imports/tickets')
```

Thanks in advance for any suggestions.

**Comment by mwpastore** [comment]
I got this to work:

```ruby
client.tickets.request(tickets: my_tickets, :verb => :post, :path => 'imports/tickets/create_many').fetch
```

If there's a more canonical/elegant way to do it, please let me know!

**Comment by ericsaboia** [comment]
I'm trying the same with update_many, but can't make it work

**Comment by ericsaboia** [comment]
just got my issue.. I was using a pretty old version of the sdk. You should probably have access to `ZendeskAPI::Ticket.create_many`, which is defined here https://github.com/zendesk/zendesk_api_client_rb/blob/e9ddd8f504477fa62c0e1cd5a3b79f9adc84d626/lib/zendesk_api/actions.rb#L168-L182

**Comment by mwpastore** [comment]
Hi @ericsaboia, `ZendeskAPI::Ticket.create_many` calls the `tickets/create_many` endpoint, but I'm specifically trying to access the `imports/tickets/create_many` endpoint. If you'd read above you'd find my explanation of what I'm trying to do, and you'll see that my current solution is, in fact, using `create_many!` on a collection of `ZendeskAPI::Ticket` objects.

**Comment by nogates** [comment]
@mwpastore sorry for the late reply. Our client does not support importing many tickets yet, and we don't have an ETA about it either. I've created  an internal note of the request and we will review it in the future.
