### ISSUE TITLE
This gem has terrible documentation

### ISSUE THREAD

**Issue by josephecombs** [zendesk/zendesk_api_client_rb#316]
Every single resource in this gem needs a valid code example of every single CRUD action that can be performed for that resource.  Telling us to go read the core API docs is garbage.

**Comment by jgillman** [comment]
@josephecombs Agreed, though I ended up referring to the documentation here which ended up helping me figure out what kind of data I should be sending with what keys: https://developer.zendesk.com/rest_api/docs/core/tickets

You'll have to translate from the raw curl/json requests to them gem yourself though.

**Comment by Tonkpils** [comment]
@josephecombs the beauty of open source is that you can contribute to it freely. A PR instead of an issue goes a long way...specially with docs.

**Comment by josephecombs** [comment]
@Tonkpils this is a SaaS company valued at THREE BILLION DOLLARS.  They can pay some engineers to maintain this gem properly.  NO ONE should work for them for free.

**Comment by RemyMaucourt** [comment]
I do agree, my company is paying Zendesk every month, I think these fees include correct documentation.

**Comment by apanzerj** [comment]
Just because you are paying Zendesk doesn't mean anything with respect to open source software they publish. You aren't paying for this particular piece of software.

**Comment by josephecombs** [comment]
@apanzerj Sure, if you read the exact terms of the seat license payments that most companies pay zendesk, those payments are not paying for working api clients.  It's more a "spirit of the contract" thing.  The fact that this library is hosted inside their github is a testament to that reasonable assertion.

**Comment by apanzerj** [comment]
Seems like what you got here is a [case of the gimmes](https://www.amazon.com/dp/B00472OBVG). If you think this needs better documentation, make a PR, that's how this works. There is no "contract" except the Apache License this uses.

**Comment by josephecombs** [comment]
A now nearly THREE BILLION DOLLAR company should maintain these tools.  Yes, I do expect a company that is deeply integrated SaaS in many, many firms to maintain clients in major languages.  Your posting basically irrelevant accusations here is a major distraction from the important issue raised.

**Comment by apanzerj** [comment]
I still don't understand why you won't make a PR and help out.

**Comment by josephecombs** [comment]
Fair enough, maybe I am being overly critical and I may make a PR. 

There were a lot of idiosyncrasies, from what I recall. I do not remember the exact reason why I opened this issue in the first place, nor do I work at the company where I used this tool.

**Comment by apanzerj** [comment]
Side note: I am not disagreeing. The docs are shit. I had the very same issues and I was new to ruby at the same time too.

**Comment by RemyMaucourt** [comment]
Problem is, having access to a client in the langage I use was a part of the reason I choose Zendesk in the first place. The fact that it's open source is not an excuse. This gem, and its documentation, are part of the service that Zendesk provide, and which I'm paying them for.

Let's be clear: I'm way more concerned about the poor code quality than the lack of documentation. I guess these two problems are linked, it just shows a lack of interest.

**Comment by RemyMaucourt** [comment]
My disappointment is due to the fact that I blindly choose this gem because it's the official one. I thought that being maintained by zendesk team was a quality label, I was wrong.

**Comment by imi-milaap** [comment]
> @josephecombs the beauty of open source is that you can contribute to it freely. A PR instead of an issue goes a long way...specially with docs.

Yeah, that's true but without proper documentation, I am not able to start man.

**Comment by jaequery** [comment]
Is there a document page up now? I see this ticket goes way back, surely there must be some doc, am I missing something?

I want to search for tickets created by a certain user and I'm confused how to do this.

I tried client.tickets.search(:submitter_id => id), client.tickets.find!(:submitter_id => id),  none of them work. What am i supposed to pass?

**Comment by ggrossman** [comment]
@jaequery, you may be able to get what you want by using `requested_tickets` on a `User` resource

For example:

```
irb(main):028:0> user = client.users.find!(id: user_id)
...
irb(main):029:0> tickets = user.requested_tickets
```

**Comment by jaequery** [comment]
Thanks @ggrossman but how can I see all the methods thats available under 'user'?

Right now, I need to get all the user's "assigned tickets".
I've tried user.assigned_tickets and it doesn't work.

Is there some documentation that lays them all out somewhere?

**Comment by osa-si** [comment]
> Thanks @ggrossman but how can I see all the methods thats available under 'user'?
> 
> Right now, I need to get all the user's "assigned tickets".
> I've tried user.assigned_tickets and it doesn't work.
> 
> Is there some documentation that lays them all out somewhere?

irb(main):028:0> user = client.users.methods # print all available methods

**Comment by ecoologic** [comment]
This gem is a wrapper to our API. There is no way with the current tools to auto-generate code for every verb/endpoint combination, and maintaining this manually is beyond the scope of the project. Therefore, the user is required to understand the general concepts and apply them to their needs, by relying on the API documentation.

Having that said, this gem documentation could be better, and we'll try our best to improve the documentation with every PR. We'll strive to apply the best documentation practices.

Contributions in form of documentation are very welcome, and if you encounter specific obstacles, please let us know.

We will be closing this issue, and welcome you to open new ones on targeted ones as needed.
