### ISSUE TITLE
Cache doesn't work because API always return HTTP OK

### ISSUE THREAD

**Issue by nelsonsar** [zendesk/zendesk_api_client_rb#322]
I'm not pretty sure if this repository is the right place to ask this kind of stuff, but, doing a request using cURL like the one presented below:

`curl -v --header "If-None-Match: W\/\"{E-Tag}\"" https://myapp.zendesk.com/api/v2/help_center/pt-br/sections`

Will always return a `200 OK` response even if the `E-Tag`'s match. Is this the expected result? Or the API should return a `304 NOT MODIFIED` on the subsequent requests?

**Comment by nogates** [comment]
@nelsonsar: it's probably too late already, but it's better to write to support@zendesk.com for actual issues with the API. Closing this
