### ISSUE TITLE
Wrong content type

### ISSUE THREAD

**Issue by Jerskouille** [zendesk/zendesk_api_client_rb#324]
As of today, the API started returning a `text/plain` `Content-Type` header instead of `application/json` at least on the `/articles` endpoint. (I didn't test others)
As a consequence, https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/middleware/response/parse_json.rb#L14 fails.
https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/collection.rb#L414 should raise at this point, but `fetch` is silently swallowing it: https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/collection.rb#L195 .

Here is my fix for others that need an urgent solution:
```
# Fix buggy content type of Zendesk articles
# https://twitter.com/Jerskouille/status/836268529578086401
module ZendeskAPI
  # @private
  module Middleware
    # @private
    module Response
      class ParseJson < Faraday::Response::Middleware
        def on_complete(env)
          type = env[:response_headers][CONTENT_TYPE].to_s
          type = type.split(';', 2).first if type.index(';')

          unless env[:body].strip.empty?
            env[:body] = JSON.parse(env[:body])
          end
        end
      end
    end
  end
end
```

**Comment by Jerskouille** [comment]
The app making use of the API is running on multiple subdomains where we can confirm it's failing. One example of this would be `algolia-test` .

**Comment by dpawluk** [comment]
@Jerskouille I'm not seeing this behavior on GET requests for my test zendesk instance. 

I don't believe Help Center support is actually implemented in this API in forms other than workarounds. 

see https://github.com/zendesk/zendesk_api_client_rb/issues/232

**Comment by Jerskouille** [comment]
Hi @dpawluk , that's exactly the workaround I used to get access to the articles using your client.

In the specific issue #175 , there was no mention of it not being safe to use.
While I did understand that this was unsupported, I expected it to potentially break *if* you updated the Ruby client and if I ran `bundle update`, not to simply stop working live. :)

It seems like someone on your side has since fixed the issue, because `curl` is now returning the correct `Content/Type` and my script can finally run without my monkey-patch.

**Comment by Jerskouille** [comment]
I have a question linked to this lib though: Is it expected that the `raise` [here](https://github.com/zendesk/zendesk_api_client_rb/blob/91e7a20fc3fb74446ecf9a6f1a68327fa1c97f0c/lib/zendesk_api/collection.rb#L415) is swallowed by `fetch` [here](https://github.com/zendesk/zendesk_api_client_rb/blob/91e7a20fc3fb74446ecf9a6f1a68327fa1c97f0c/lib/zendesk_api/collection.rb#L197), leading to `MyCollection.all` using an empty array in case of error?

Most API clients I've used in the past either have an option to configure if it should raise, or simply raise by default.

**Comment by Jerskouille** [comment]
I just got my answer in the README:
> note: all method calls ending in ! will raise an exception when an error occurs, see the wiki page for more info.
