### ISSUE TITLE
Faraday::SSLError: SSL_connect SYSCALL returned=5 ... on MacOS

### ISSUE THREAD

**Issue by maxforasteiro** [zendesk/zendesk_api_client_rb#325]
Hi, I'm using the zendesk API to bring all the tickets from my domain, and in the middle of the script, it breaks and return this Faraday error: `Faraday::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A` (if you guys need, i can send the full stack error). I read something on faraday gem page, and, according with the zendesk gem wiki, i set some params on my client config

```config.retry = true
      config.client_options = {
        :ssl => false,
        :request => {
          :timeout => 10000000,
          :open_timeout => 2000000
        }
      }
```

but that didn't solve my problem... I'm trying to get all the tickets from my zendesk and save all the comments and users. Can i set the timeout or ssl verification in some other way? Anyone had the same issue? Can you guys help me? PLS!

**Comment by mamantoha** [comment]
@maxforasteiro try

```
config.client_options = {:ssl => {:verify => false}}
```
