### ISSUE TITLE
Version 1.14.1 breaks ClientError class

### ISSUE THREAD

**Issue by P9GIT** [zendesk/zendesk_api_client_rb#328]
Hi.
The latest release broke one of our tests.
After some digging I discovered that the ClientError object has changed.

In 1.14.0 this works:
2.2.5 :003 > e = ZendeskAPI::Error::ClientError.new("My error message")
 => #<ZendeskAPI::Error::ClientError> 
2.2.5 :004 > e.message
  => "My error message"

In 1.14.1 I get this exception:
2.2.5 :003 > e = ZendeskAPI::Error::ClientError.new("My error message")
 => #<ZendeskAPI::Error::ClientError> 
2.2.5 :004 > e.message
ArgumentError: wrong number of arguments (0 for 1)
	from /home/tb/.rvm/gems/ruby-2.2.5@rails41/gems/zendesk_api-1.14.1/lib/zendesk_api/error.rb:8:in `method'
	from /home/tb/.rvm/gems/ruby-2.2.5@rails41/gems/zendesk_api-1.14.1/lib/zendesk_api/error.rb:8:in `to_s'
	from (irb):4:in `message'
	from (irb):4
	from /home/tb/.rvm/gems/ruby-2.2.5@rails41/gems/railties-4.1.16/lib/rails/commands/console.rb:90:in `start'
	from /home/tb/.rvm/gems/ruby-2.2.5@rails41/gems/railties-4.1.16/lib/rails/commands/console.rb:9:in `start'
	from /home/tb/.rvm/gems/ruby-2.2.5@rails41/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/tb/.rvm/gems/ruby-2.2.5@rails41/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/tb/.rvm/gems/ruby-2.2.5@rails41/gems/railties-4.1.16/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>

Is this intended by the update?

Best regards,
Thomas Balsløv

**Comment by bquorning** [comment]
cc @grosser

**Comment by grosser** [comment]
that error was not really intended to be used without a response ... but does not hurt to make it work either ... fixed in https://github.com/zendesk/zendesk_api_client_rb/pull/329

**Comment by grosser** [comment]
1.14.2

**Comment by P9GIT** [comment]
Hi @grosser 
Thanks for the update!
