### ISSUE TITLE
Merging users from api client

### ISSUE THREAD

**Issue by ldrbrandon** [zendesk/zendesk_api_client_rb#330]
Is there a way to merge users from the API client? It looks like there is a way to do this with tickets but not with users. The code in `lib/zendesk_api/resources.rb, line 433` looks simple enough but I know merging user's is different.

Are there plans to support this or do I need to implement on my own?

**Comment by dladowitz** [comment]
Same question, we've got thousands of duplicate end users because phone calls and email requests are not synced up. We are going to start looking up and merging at the time of request. 
We currently use this ruby client. I'd like to avoid also implementing the traditional HTTP API.

**Comment by kevinjcoleman** [comment]
@ldrbrandon @dladowitz did you guys ever figure this out?
