### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by epinault** [zendesk/zendesk_api_client_rb#332]
Hi! 

It would be nice to have changelog that follow this http://keepachangelog.com/en/0.3.0/

Makes it easier for update/upgrade decision

Thanks

**Comment by P9GIT** [comment]
@epinault.

Indeed a good idea! +1 from me.

**Comment by elenatanasoiu** [comment]
+1 on this

**Comment by ggrossman** [comment]
We've now merged @elenatanasoiu 's contribution, https://github.com/zendesk/zendesk_api_client_rb/pull/339
