### ISSUE TITLE
undefined local method `disable_warnings'

### ISSUE THREAD

**Issue by JIucToyxuu** [zendesk/zendesk_api_client_rb#333]
On start web-server i have next error log:

`rescue in block (2 levels) in require': There was an error while trying to load the gem 'zendesk_api'. (Bundler::GemRequireError)
Gem Load Error is: undefined local variable or method `disable_warnings' for ZendeskAPI::SilentMash:Class

**Comment by nogates** [comment]
I am sorry we haven't replied to this issue in two years. I am gonna close it now but do not hesitate to open it again if the problem continues.
