### ISSUE TITLE
Cache on production

### ISSUE THREAD

**Issue by leakira** [zendesk/zendesk_api_client_rb#341]
Hello

I disabled client cache by setting config.cache as nil, and in localhost the cache is disabled, but in production the cache continues.
Has a other configuration setting to disable cache on production?

Thanks in advance

**Comment by nogates** [comment]
Hi @leakira ! Sorry for the late reply! As per configuration, setting cache to `false` disables the cache completely (https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/configuration.rb#L41)... and that should be the same for all environments...

I am gonna close this, but do not hesitate to open it again if you are still having some issues with it
