### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by atulmishra-cleartax** [zendesk/zendesk_api_client_rb#352]
Hi,

 i am pretty to new to ruby on rails and i was setting up zendesk app in ruby on rails for my company. 
I did exactly what is written in wiki but getting error that i am not able to resolve. 

error - NoMethodError Exception: undefined method `connection' for #<ZendeskService:0x*******a9a0>

line that i am executing is - ZendeskAPI::Ticket.find(zendesk_client, :id => 506221)

here , printing zendesk_client is printing proper values , not able to resolve error. 

Note :- Figured out that i am not able to call any functions in this api , for ex -  zendesk_client.tickets
is throwing error - NoMethodError Exception: undefined method `tickets' for #<ZendeskService:0x******a9a0>
Thanks in advance.

**Comment by jpalmieri** [comment]
I'm not sure what's happening here, but it might be helpful to post the configuration that you're using, just to be sure (but exclude sensitive information, of course).

Also, since you're initializing the client within a Rails app, it also might be helpful to detail how you're doing that, or at least pointing to the resource that you're using as a guide to do that. Thanks!

**Comment by atulmishra-cleartax** [comment]
Configuration file contents :- 

`
require 'zendesk_api'

class ZendeskService

  @client = nil

  def initialize
    @client = ZendeskAPI::Client.new do |config|

      config.url = "https://*****.zendesk.com/api/v2" 
      config.access_token = "**********************"
      # Optional:
      config.retry = true
      require 'logger'
      config.logger = Logger.new(STDOUT)

    end
    @clientz
  end

  def get_client
    @client
  end

end

`


And main file contents are :- 

  ` 
    zendesk_client = ZendeskService.new() 
   #This calls the upper service file to get content

    logger.info "Getting Client :: #{zendesk_client}"
    #getting the client id here

   tickets = zendesk_client.tickets 
#getting error here that no method error for zendesk_client
#same here getting for every call method

`


Thanks

**Comment by jpalmieri** [comment]
@atulmishra-cleartax You're almost there. The problem is that the `initialize` method isn't actually returning the client (I assume that's what you were trying to do with the `@clientz` at the end of it). You could return it by calling the `get_client` method after instantiating the object. Try this:

```.ruby
require 'zendesk_api'

class ZendeskService
  def initialize
    @client = ZendeskAPI::Client.new do |config|
      config.url = "https://*****.zendesk.com/api/v2"
      config.access_token = "**********************"
      # Optional:
      config.retry = true
      require 'logger'
      config.logger = Logger.new(STDOUT)
    end
  end

  def get_client
    @client
  end

end

zendesk_client = ZendeskService.new().get_client
tickets = zendesk_client.tickets
```

**Comment by atulmishra-cleartax** [comment]
thanks a lot @jpalmieri , it did my work :) .

**Comment by atulmishra-cleartax** [comment]
hi @jpalmieri  , 

 I have successfully configured , But now i am getting error even after providing the correct Oauth access token. 

For ex - 
 curl -H "Authorization: Bearer ********************************" https://obscura.zendesk.com/api/v2/users.json

gives error :- {"error":"invalid_token","error_description":"The access token provided is expired, revoked, malformed or invalid for other reasons."}

For ex:- executing 
clients.tickets.first is giving the same error for me, i have rechecked the token as well change it and provided again , still getting same error.

**Comment by jpalmieri** [comment]
@atulmishra-cleartax You should probably contact Zendesk Support for help with sorting this out; if you're getting the error using `curl`, it's definitely not and error related to this gem.

**Comment by atulmishra-cleartax** [comment]
yeah finally resolved the error. Closing it now .

Thanks for help :)
