### ISSUE TITLE
Support hash input for client creation

### ISSUE THREAD

**Issue by Karamorf** [zendesk/zendesk_api_client_rb#353]
Currently ZendeskAPI::Client only supports code blocks for instantiation, it should also support hash inputs so I can do this:
```
ZendeskAPI::Client.new({
  :username => 'user',
  :url => 'zendesk url',
  :token => 'token
})
```

This will also make inheritance easier if I wanted to wrap the client and customize for my own needs. I was able to accomplish this by creating a class like this:

```
class Etzendesk < ZendeskAPI::Client
  def initialize(args)
    super() do |config|
      args.each do |field, value|
        config.send("#{field}=", value)
      end
    end
  end
end
```

I shouldn't have to do that.

The use case is my company runs several Zendesk instances. Instead of having to have a different instantiation for each one, I created an object factory that reads in a YAML file and gives that to the above class as a hash. This simplifies my code setup and makes it super easier to connect to multiple zendesk API's within the same scope.

**Comment by ecoologic** [comment]
It's a good idea, but we need to carefully manage our time. Your workaround is not ideal but it works. Maybe if this issue gets more traction we can re-consider it.

Thank you for your suggestion.
