### ISSUE TITLE
ZendeskAPI::Error::NetworkError: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by myckel** [zendesk/zendesk_api_client_rb#365]
Hello i get the error ZendeskAPI::Error::NetworkError: Connection reset by peer - SSL_connect when i try to create a new ticket this is my code, this only happen in production in dev i can create tickets 

`client = ZendeskAPI::Client.new do |config|
        config.url = ENV['ZENDESK_URL']
        config.username = ENV['ZENDESK_USER']
        config.token = ENV['ZENDESK_TOKEN']
        config.retry = true
      end`
`response  = ZendeskAPI::Ticket.create!(client,:subject => "Ticket"}",:comment => {:value => body },:requester => {:name=> name,:email => email},:assignee_id => id,:recipient => suport_mail,:group_id => group_id)`

**Comment by nogates** [comment]
@myckel Sorry for the late reply (a bit more of 1 year late). This sounds like a SSL configuration issue, like this related feature: https://github.com/zendesk/zendesk_api_client_rb/issues/195

I am gonna close this one, but do not hesitate to open it again if you are still having this problems or you have any other question
