### ISSUE TITLE
Bulk importing organizations

### ISSUE THREAD

**Issue by amalhao** [zendesk/zendesk_api_client_rb#366]
Is it possible to add bulk import for organizations? 

As described here: https://developer.zendesk.com/rest_api/docs/core/organizations#create-many-organizations

Thanks

**Comment by nogates** [comment]
Sorry for the late reply @amalhao ! This has been added to the version 1.22.0 (https://github.com/zendesk/zendesk_api_client_rb/pull/406).

I am gonna close this, but do not hesitate to add a comment if you have any other question
