### ISSUE TITLE
Suspended user error formatting

### ISSUE THREAD

**Issue by piotr-sokolowski** [zendesk/zendesk_api_client_rb#369]
Currently when trying to submit a ticket as suspended user (named in this example as "Contact Form" the error is

```
ZendeskAPI::Error::RecordInvalid: {"requester"=>[{"description"=>"Requester: Contact Form is suspended."}]}
```

Due to specific requester name that may be confusing it would be great if the error message was slightly changed to for example:

```
ZendeskAPI::Error::RecordInvalid: {"requester"=>[{"description"=>"Requester: 'Contact Form' is suspended."}]}
```

or as Zendesk support suggested to:
```
ZendeskAPI::Error::RecordInvalid: {"requester"=>[{"description"=>"Requester: User 'Contact Form' is suspended."}]}
```

**Comment by ecoologic** [comment]
I agree the error could be improved. This message however comes from the API response. I have suggested the relevant team this improvement.

Thank you for your help making the gem better.
I wish we answered to you earlier.
Have a nice day.
