### ISSUE TITLE
Add more methods for working with collections like tags

### ISSUE THREAD

**Issue by hkmaly** [zendesk/zendesk_api_client_rb#371]
There is << method implemented on collections, but nothing for removing items from them ; array methods mostly works due to method_missing, but behaviour is not exactly predictable.

Specifically, I was trying to use + and - on tags and it didn't thrown any errors, but it resulted in duplicities, probably because the string tags I was adding/removing were not wrapped.

Note that currently I'm using << and reject! ...

**Comment by nogates** [comment]
Thanks for the suggestion @hkmaly! But, I am gonna close this since we won't be implementing any of these methods soon!
