### ISSUE TITLE
Username/Password auth doesn't work

### ISSUE THREAD

**Issue by JohnBDonner** [zendesk/zendesk_api_client_rb#376]
Starting today at around 10:30 UTC, the connection to the Zendesk API via username/password auth stopped working, and our code was unable to fetch tickets through it. We were able to fetch the same Zendesk tickets by changing our API auth to use the username/token auth. 

If username/password auth isn't supported anymore, then the documentation here should reflect that.

To put it simply:

Not working:
```ruby
ZendeskAPI::Client.new do |config|
  config.url = zendesk_api_url
  config.username = zendesk_api_username
  config.password = zendesk_api_password
  config.retry = true
end
```

Working:
```ruby
ZendeskAPI::Client.new do |config|
  config.url = zendesk_api_url
  config.username = zendesk_api_username + "/token"
  config.token = zendesk_api_token
  config.retry = true
end
```

**Comment by ggrossman** [comment]
Hi @JohnBDonner,

Pardon the slow reply. Username/password authentication is still supported through the API. I just tested it out on a test account and it is still working. We wouldn't take this away without an official announcement and a deprecation period.

There is a setting that needs to be enabled in Settings / Channels / API in the Zendesk Admin; are you certain that this setting is enabled? Perhaps it got turned off somehow. Also, are you certain the password was not changed?

Here's a screenshot of the relevant setting:

<img width="788" alt="Screenshot 2019-04-05 10 32 19" src="https://user-images.githubusercontent.com/5636481/55645801-656b1580-578e-11e9-9ba5-04f5445e8f27.png">

Gary Grossman
Senior Principal Engineer, Zendesk

**Comment by nogates** [comment]
@JohnBDonner I am gonna close this since your question has been already answered, but do not hesitate to open it again if you any extra information
