### ISSUE TITLE
Broken Travis CI builds

### ISSUE THREAD

**Issue by rcscott** [zendesk/zendesk_api_client_rb#377]
Builds are failing in Travis CI because the [new version of Bundler](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html) dropped support for Ruby < 2.3. I think there are two options for fixing this:

1. Fix the Travis configuration so that we install an older version of Bundler when testing old versions of Ruby.
1. Drop support for old versions of Ruby < 2.3.

My personal opinion would be that the old versions of Ruby should be dropped since they have all been marked End-of-Life. Ruby 2.2 has been EOL for almost a year, and the other versions for much longer.

I'm happy to submit a PR for either solution but wanted to check with maintainers on which path is preferred.

**Comment by ggrossman** [comment]
Hi @rcscott , thanks for the report. I agree that this gem does not need to support EOL versions of Ruby that even Bundler is no longer supporting, and that would be preferable to force-installing an old version of Bundler. We'd be happy to receive a PR from you for this.

Gary Grossman
Senior Principal Engineer, Zendesk

**Comment by ggrossman** [comment]
Hi @rcscott , we have a PR for this up for now at https://github.com/zendesk/zendesk_api_client_rb/pull/378

**Comment by rcscott** [comment]
Wow that was fast, you beat me to it! Thanks @ggrossman for the speedy work.
