### ISSUE TITLE
How to retrieve the ticket's comments?

### ISSUE THREAD

**Issue by jaequery** [zendesk/zendesk_api_client_rb#379]
Hi, I can't figure out how to retrieve the ticket's comments using the SDK. can someone please help me here? thanks!

**Comment by yachtcaptain23** [comment]
you can retrieve like the following:

```
    for index in (0...client.ticket.find(id: zendesk_ticket_id).comments.count)
      comment = client.ticket.find(id: zendesk_ticket_id).comments[index]
    end
```

**Comment by nogates** [comment]
I think we can close this, feel free to open it again if you have any more questions
