### ISSUE TITLE
Does this gem support soft deletion _and_ permanent deletion?

### ISSUE THREAD

**Issue by issyl0** [zendesk/zendesk_api_client_rb#383]
Apparently the Zendesk API has two sets of deletes on both users and tickets, "soft delete" that puts the deleted things into a separate queue, then a "permanent delete" that actually gets rid of them from the deleted queue.

Does this gem support `DELETE /api/v2/{tickets,users}/{id}.json` _and_ `DELETE /api/v2/deleted_{tickets,users}/{id}.json`? I can't find a `deleted_tickets` or `deleted_users` method, which I'd expect if this gem matched the API docs?

I have looked at the code to figure out what eg`client.ticket.destroy!` does, but I can't tell if it does "soft delete" or "permanent delete".

Can anyone advise, please? Am I missing something really obvious?

**Comment by dbuskariol** [comment]
Hey @issyl0 👋 Did you happen to figure out how to hit the [`deleted_tickets`](https://developer.zendesk.com/rest_api/docs/support/tickets#list-deleted-tickets) endpoint using this gem?

**Comment by issyl0** [comment]
@dbuskariol Hi! 👋I didn't figure it out, no. Have you managed to?

**Comment by issyl0** [comment]
The gem doesn't do this itself, and there haven't been any updates from Zendesk on this issue since I opened it in May, so I'm going to close this.

We solved this in our script by soft deleting users with the API client, and then permanently deleting users by querying the API with `RestClient`:

```
RestClient::Request.execute method: :delete, url: "https://example.zendesk.com/api/v2/deleted_users/#{user_id}.json", user: example, password: example
```

**Comment by cap3618** [comment]
I don't know how to use api. Can you help me?

**Comment by sameera207** [comment]
thanks, @issyl0 this worked for me. If anyone come across with this same issue, it turns out you can't directly delete the tickets permanently.  You'll have to first `soft` delete the tickets and then delete them permanently. 

So, my code ended up something like this

```
@client.tickets.destroy_many!(ids) # this is the soft delete part using the the gem's own method

# hard delete 
RestClient::Request.execute(
      method: :delete,
      url: "https://#{@zendesk_url}.zendesk.com/api/v2/deleted_tickets/destroy_many.json?ids=#{ids.join(',')}",
      user: @username,
      password: @password
    )
```
This can be refactor a bit, but just posting here so that it might steer someone in the right direction.
