### ISSUE TITLE
Is there a way to add attachment file from content string

### ISSUE THREAD

**Issue by razbensimon** [zendesk/zendesk_api_client_rb#384]
Can I add an attachment file from string of content ? (not from File instance)
I dont want to use Tempfile or File.

like: (and how should I add the file name?)
```
ticket.comment.uploads << params[:logs]
ticket.save!
```

Thanks

**Comment by nogates** [comment]
Hello @razbensimon 

Zendesk api client uses Faraday as http client and the `Faraday::UploadIO` class to provide the uploading functionality. So theoretically, you could use [StringIO](https://ruby-doc.org/stdlib-2.6.3/libdoc/stringio/rdoc/StringIO.html) class to pass a string. However, if you do that, you would still need to pass the filename in the request, which cannot be guessed from a `StringIO` instance.

The [Upload Middleware](https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/middleware/request/upload.rb) provided within in the gem, gets these values from a File instance. So, unfortunately, if you want to use the gem as it is, you need to provide a File instance or a file path to the `uploads` accessor. 

I am gonna close this issue, but feel free to open it again if you have any further questions.
