### ISSUE TITLE
Request header requirements for Marketplace apps

### ISSUE THREAD

**Issue by Krustal** [zendesk/zendesk_api_client_rb#385]
What would be the most idiomatic method for conforming to the requirement for request headers covered in this post? https://develop.zendesk.com/hc/en-us/articles/360001934648

**Comment by nogates** [comment]
Hello @Krustal 

You can access / modify the default headers used in all request using the `client.connection.headers` accessor

```ruby
[4] pry(main)> client.connection.headers
=> {"Accept"=>"application/json", "Accept-Encoding"=>"gzip;q=1.0,deflate;q=0.6,identity;q=0.3", "User-Agent"=>"ZendeskAPI Ruby 1.20.0"}
```

Does this answer you question?

**Comment by nogates** [comment]
Going to close this, but do not hesitate to open the issue again if you have more questions
