### ISSUE TITLE
zendesk api is ssl only when trying to pass in a URL from a config file

### ISSUE THREAD

**Issue by rfdunn** [zendesk/zendesk_api_client_rb#400]
Similiar to this: https://github.com/zendesk/zendesk_api_client_rb/issues/244, but my syntax is correct as I can get it working.

I'm trying to load my settings from a separate file

> require 'yaml'
> require 'zendesk_api'
> 
> client = ZendeskAPI::Client.new do |config|
>   configobject = YAML.load_file("config.yml")
>   config.url = configobject['url']
>   config.username = configobject['username']
>   config.token = configobject['token']
>   config.retry = true
> end

and the yaml:

> #config.yml
>
> url : "https://urltomyzendesk/api/v2"
> username : "username"
> token : "token"

This doesn't work, it doesn't like the URL, I get the "zendesk api is ssl only".

Now if I hard code the URL so it becomes
> client = ZendeskAPI::Client.new do |config|
>   configobject = YAML.load_file("config.yml")
>   config.url = "https://myzendeskurl/api/v2"
>   config.username = configobject['username']
>   config.token = configobject['token']
>   config.retry = true
> end

it works.

**Comment by drop-ivan** [comment]
I have the same issue, even when I hard code the URL

**Comment by nogates** [comment]
Hello @rfdunn and @drop-ivan! 

could it be possible that you are passing an empty string or nil to the config? if that's the case, the `check_url` method will raise an exception:
https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/client.rb#L195-L199

@rfdunn  Could you please print out the content of `configobject`? as it's returned from `YAML.load_file("config.yml")`

**Comment by rfdunn** [comment]
I found out my issue was that the YAML wasn't loading properly. I don't know if this was a side product of Linux on Windows as a subsystem or something else but after numerous reboots (for other purposes) this started working. So not satisfactory but a result nonetheless.

**Comment by nogates** [comment]
I am glad that is working now! I am going to close this issue since seems resolved, but do not hesitate to add more comments if you have more questions.
