### ISSUE TITLE
Can't find organization by name

### ISSUE THREAD

**Issue by hcuong** [zendesk/zendesk_api_client_rb#401]
Hi guys, 

I can't find how to search an organization by name though that field is unique.

Try with search like 
`client.organizations.search(query: "Org name").fetch`
or 
`client.organizations.search(name: "Org name").fetch`

I got this message 
` WARNING: Removed restricted keys ["query"] from parameters according to whitelist`

is that function available? if not should it be exist?

**Comment by nogates** [comment]
Hello @hcuong !!

You need to use the `Search` endpoint for this (https://developer.zendesk.com/rest_api/docs/support/search#query-basics). E.G:

```
[1] pry(main)> client.search(query: "type:organization name:Zendesk").to_a
=> [#<ZendeskAPI::Organization {...}]
```

The search on the organizations resource only works with `external_ids`: https://developer.zendesk.com/rest_api/docs/support/organizations#search-organizations-by-external-id

I hope this helps!

**Comment by hcuong** [comment]
yeah, it helps much. I am using search for external_ids. Will try with query field. Thank you!
