### ISSUE TITLE
Hard dependency on Faraday 0.9.x

### ISSUE THREAD

**Issue by romikoops** [zendesk/zendesk_api_client_rb#410]
zendesk_api.gemspec file contains this line of code

```ruby
s.add_runtime_dependency "faraday", "~> 0.9"
```

Current Faraday version is `0.17.1` (https://rubygems.org/gems/faraday)

What the motivation to limit the gem within faraday `0.9.x`? I saw there were problems with faraday 0.8, but in that case it must be:

```ruby
s.add_runtime_dependency "faraday", ">= 0.9.0", "< 1.0.0"
```

Actually, currently `zendesk_api` gem is not compatible with `google-cloud-ruby` gem, which is official gem for Rails Active Storage https://edgeguides.rubyonrails.org/active_storage_overview.html#google-cloud-storage-service

**Comment by nogates** [comment]
Merged the PR! thanks for the contribution @romikoops ! Closing this
