### ISSUE TITLE
New release for zendesk_api_client

### ISSUE THREAD

**Issue by flaviovisetti** [zendesk/zendesk_api_client_rb#424]
Any ideia when will be create release for the last updates? Ex: Faraday update...
Without this new release many other gems does not work with `zendesk_api_client`. 

ex: `gem 'elasticsearch', '~> 7.6.0'`

**Comment by tanelsuurhans** [comment]
The lack of a release to address the Faraday update is starting to hard-block some other dependencies.

**Comment by nogates** [comment]
I am so sorry it has taken me such a long time to release the latest version. I had just pushed it to rubygems.
