### ISSUE TITLE
Search api doesn't accept sort_by and sort_order

### ISSUE THREAD

**Issue by ghost** [zendesk/zendesk_api_client_rb#459]
This query returns `[]`
```
Zendesk.client.search(query: "type:ticket sort_by:created_at sort_order:asc")
```

But [docs](https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/#list-search-results) had these params. If Zendesk can't maintain a consistent state with docs, just expose a method we could use to send direct queries to these APIs

If this isn't a great solution, should we go this route instead?
```
search = Zendesk.client.search(query: "type:ticket)
search.sort_by('created_at').sort_order('asc')
```
Am asking because I could take time to implement this feature.

**Comment by ecoologic** [comment]
The intended way of using the order params is:

```ruby
@ts = []
client.search(query: "type:ticket", sort_by: :created_at, sort_order: :asc).all { |t| @ts << t.created_at }
# @ts will be ordered
```

Have a good day,
wherever you are now.
