### ISSUE TITLE
Does this API supports for cursor pagination

### ISSUE THREAD

**Issue by KevinPedroza** [zendesk/zendesk_api_client_rb#461]
I am migrating from offset to cursor pagination, but it looks that this API does not support this. 

Is it right? And if so, will it add support for this change?

**Comment by jennifer-kinsey** [comment]
With the Sept 15 move to cursor based pagination, I would also like to know this.

**Comment by KevinPedroza** [comment]
> With the Sept 15 move to cursor based pagination, I would also like to know this.

I already sent a PR with some changes for the cursor pagination. You can check it out on the open PR.

**Comment by KevinPedroza** [comment]
https://github.com/zendesk/zendesk_api_client_rb/pull/463
Here you can find it, you can fork it if you want.

**Comment by ecoologic** [comment]
Solved by merged PR.

Thank you, @KevinPedroza!
