### ISSUE TITLE
Searching help center articles with this API? 

### ISSUE THREAD

**Issue by aaronpurt** [zendesk/zendesk_api_client_rb#468]
Hi,

Hoping someone help. The documentation doesn't go into details on interacting with help center articles. 

On Zendesk API searching help center articles we would be able to call: 
https://example.zendesk.com/api/v2/help_center/articles/search.json?query=test&page=1&per_page=25. 

I have setup the client config with url, login info. 
But, how do we go about searching the help center articles in this ruby gem? The documentation isn't very clear how to interact with help center articles. Have tried numerous ways without success. 

Example: client.articles.fetch!(:query => "test") will return 30 results in an array. And it doesn't seem to be filtering correctly. 
But, the result is missing: count, next_page, previous_page.

**Comment by tythorsen-drip** [comment]
@aaronpurt I'm in the same boat. There doesn't seem to be a clear way to search for Guide/Help Center articles. Nothing I've tried so far results in requests to the endpoint suggested by the API docs: `https://{subdomain}.zendesk.com/api/v2/guide/search?`. (from https://developer.zendesk.com/api-reference/help_center/help-center-api/search/)

Zendesk team, would appreciate a response on this.

**Comment by ecoologic** [comment]
@tythorsen-drip and @aaronpurt - you can try out the new feature pointing to the master branch.
