### ISSUE TITLE
with 2fa (two factor authentication) unable to initialize zendesk client 

### ISSUE THREAD

**Issue by nishajgd** [zendesk/zendesk_api_client_rb#501]
We are using zendesk_api client since few years and everything was working as expected.

Now everything stopped as we enabled 2fa for the domain. 

Do we have any idea our ruby client supports 2fa or not.

Thank you!

**Comment by ecoologic** [comment]
Thank you for bringing this to our notice. We will consider support for this.

**Comment by ecoologic** [comment]
@nishajgd - we might have found a window of time to investigate your issue. What is your account? What HTTP library are you using?

Thank you.

**Comment by Zendesk-NathanBellette** [comment]
@nishajgd You will need to use an API token if you have 2FA enabled. You can find more information about using the API with 2FA here: https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/using-the-api-with-2-factor-authentication-enabled/
