### ISSUE TITLE
is there a trick to running the specs?

### ISSUE THREAD

**Issue by rsl** [zendesk/zendesk_api_client_rb#502]
i've created a fork to try to resolve the dependency on out-of-date Faraday. however, immediately after `bundle install`, running the tests gives me a mess of errors.

```
Finished in 0.00004 seconds (files took 0.35452 seconds to load)
0 examples, 0 failures, 32 errors occurred outside of examples
```

i have little faith that there are humans actively monitoring/managing this software right now (as most threads, specifically those around Faraday are completely unaddressed/replied to) but thought i'd ask this question.

**Comment by codealchemy** [comment]
I am able to run tests using either `rake spec` (which is what's used in CI, see [ref in the readme](https://github.com/zendesk/zendesk_api_client_rb#running-the-gem-locally)) or `rspec spec/core`.

There is a separate task that will run tests against a live instance of Zendesk (`rake spec:live`. though that requires some setup for credentials that doesn't appear to be documented here)

https://github.com/zendesk/zendesk_api_client_rb/blob/86534b5bc5a9aac974a5759a53d73f7c33bb56c7/Rakefile#L12-L21

What is the error output if you try to run tests for a single file?

**Comment by rsl** [comment]
so so many issues... the biggest/reddest is
```
An error occurred while loading ./spec/live/webhook_spec.rb.
Failure/Error: dependency 'json'

NoMethodError:
  undefined method `dependency' for ZendeskAPI::Middleware::Request::EncodeJson:Class

          dependency 'json'
```

**Comment by rsl** [comment]
try removing yr previously working `Gemfile.lock` [which isn't in version control] and generating from scratch

**Comment by rsl** [comment]
you can see what i end up with here: https://gist.github.com/rsl/6ab47ca0b8f20335a40d0009baea077f

**Comment by codealchemy** [comment]
Ah, first guess is a Ruby version issue - it looks like [you're using `2.3`](https://gist.github.com/rsl/6ab47ca0b8f20335a40d0009baea077f#file-gistfile1-txt-L160) (which is the minimum for this project, and should likely be updated given it's pretty out-of-date) - but is incompatible with a number of gems in the lockfile you linked (`rails@7.0` being one).

The minimum Ruby version used in CI is 2.6

https://github.com/zendesk/zendesk_api_client_rb/blob/86534b5bc5a9aac974a5759a53d73f7c33bb56c7/.github/workflows/main.yml#L16-L22

📝 I had run my earlier checks using `3.0` (on an M1 mac)

**Comment by rsl** [comment]
looks like it's using the system ruby not chruby for some reason. good catch. when i ran with `bundle exec rspec` it gets different errors but doesn't freak the heck out at least. explains some of it, right?  gotten used to not having to `bundle exec` everything manually in most of my projects.

glad to see there's humans around as well. any chance some of them/y'all are looking at upgrading to a modern Faraday? there's been several threads about it but zero replies. i get how OSS works and how not every request merits attention and all.

**Comment by rsl** [comment]
isn't the `bundled with` line tho a reference to the version of bundler, not Ruby?

i get 
```
BUNDLED WITH
   2.3.20
```
when i `bundle exec bundle install` as well because 
```
zendesk_api_client_rb on  master [$?] via 💎 ruby-3.1.2 
➜ bundle --version          
Bundler version 2.3.20

zendesk_api_client_rb on  master [$?] via 💎 ruby-3.1.2 
➜ ruby --version 
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
```

**Comment by rsl** [comment]
sure thing
