### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [zendesk/zendesk_api_client_rb#516]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Zendesk plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Zendesk data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by ecoologic** [comment]
G’day Yevgeny,

Thank you for reaching out to us about your new integration with our product. I appreciate your hard work and dedication in creating something that is valuable, useful and well-made. I am impressed by your expertise and would like to commend you for your efforts.

However, after careful consideration, I must advise you that we are unable to take on the ownership of the integration at this time or later. Our focus is currently on other priorities and I do not want to overburden our team.

Please know that we are still very interested in your integration and would be happy to support you in any way we can. Our goal is to ensure a smooth experience for our users and we believe that your integration can play an important role in that.

Thank you again for reaching out to us and I hope we can continue to collaborate in the future.

Best regards

**Comment by yevgenypats** [comment]
Hey @ecoologic Thanks for the message and the warm words!

I've a question, if we will write and maintain the plugin at least initially. Will you be able to help us with marketing efforts as essentially it's mostly for ZenDesk users? For example putting us under the `Data` section [here](https://developer.zendesk.com/documentation/developer-tools/working-with-data/getting-large-data-sets-with-the-zendesk-api-and-python/) as Exporting data to data-lakes and link to CloudQuery (of-course with a note that this is a community tool).
