### ISSUE TITLE
Client does not have new Omnichannel/Agent Availability API

### ISSUE THREAD

**Issue by ryonday** [zendesk/zendesk_api_client_rb#562]
[See](https://developer.zendesk.com/api-reference/agent-availability/introduction/)

**Comment by ecoologic** [comment]
We're planning to implement this.

**Comment by fbvilela** [comment]
Hi @ryonday, 

It's been a long time but here it is https://github.com/zendesk/zendesk_api_client_rb/pull/575

Can you please take a look at the section added in the `README` file that explains the usage and let me know if you're happy with it 🙏

**Comment by ecoologic** [comment]
Fix available in v3.1.0, enjoy!
