### ISSUE TITLE
Deprecation of password access to APIs

### ISSUE THREAD

**Issue by jrmhaig** [zendesk/zendesk_api_client_rb#577]
According to [this announcement](https://support.zendesk.com/hc/en-us/articles/7386291855386-Announcing-the-deprecation-of-password-access-for-APIs) the password access to the API is being deprecated. The `README.md` file still lists this an a possible configuration option with no further comment. I was initially concerned that this meant that the 'token' access, which we currently use, was being deprecated but I now see that 'password' and 'token' are two separate methods.

Would you consider updating the documentation to make it clear which options are available, which are being deprecated (and when) and what is recommended. Thanks.

**Comment by Zendesk-NathanBellette** [comment]
HI @jrmhaig, Apologies for the late reply. The documentation should now be updated. Please let me know if you spot anything we have missed.
Kind regards,
Nathan

**Comment by jrmhaig** [comment]
Thanks, @Zendesk-NathanBellette . Can you please give a link to the documentation that has been updated?

The notes I was referring to are here:

https://github.com/zendesk/zendesk_api_client_rb/blob/63f0ffe888d93fece6822047e69c291c4d7c2436/README.md?plain=1#L62-L64

This is in the `README.md` file of this repository and it suggests using a token or password as equally valid options with no mention that password authentication is deprecated and will be removed soon.

**Comment by Zendesk-NathanBellette** [comment]
Ah, I see what you mean. Apologies for the confusion. I have now updated `README.md` accordingly. Please let me know if you find any other issues,

**Comment by Zendesk-NathanBellette** [comment]
Closing until further assistance required.
