### ISSUE TITLE
Searching be external_id doesn't return a result

### ISSUE THREAD

**Issue by keithpitt** [zendesk/zendesk_api_client_rb#80]
The scenario is:
- I create a Zendesk Ticket with an `external_id`
- I immediately try to lookup that ticket with the same `external_id` and get no results
- I wait 10 minutes or so, and its starts showing up.

``` ruby
external_id = SecureRandom.uuid
  #=> "7cfde8e8-5004-4911-9d62-e21e68447d9b"

zendesk_ticket = ::ZendeskAPI::Ticket.new(ZENDESK_CLIENT, {
  :subject => subject,
  :group_id => group_id,
  :external_id => "1234-5678",
  :comment => {
    :value => comment,
    :public => false
  },
  :requester => {
    :name => name,
    :email => email
  }
})

zendesk_ticket.save

found_ticket = ::ZendeskAPI::Search.search(ZENDESK_CLIENT, {
  :query => "type:ticket external_id:#{external_id}"
}).first

# found_ticket will be nil here
```

**Comment by maxkwallace** [comment]
@jwswj does the 10 minute delay apply to searching Users?

**Comment by jwswj** [comment]
@maxkwallace The delay does, and can be anywhere between 1-10mins due to the way our search indexing currently works. We have a project to rebuild our indexer pipeline, however it's a big project so it won't drop for a while. What's your use case, maybe there is a workaround...

**Comment by maxkwallace** [comment]
@jwswj thanks for the reply! I can work around this using the existing API, but this delay should definitely definitely definitely be reflected in the docs (e.g. https://developer.zendesk.com/rest_api/docs/core/search). It's very frustrating to try to design around limitations like this when they're buried in GitHub issues.

**Comment by jwswj** [comment]
I've raised the issue with the search team so hopefully it can be mentioned on that page @maxkwallace.
